import { bg,title,button } from '../ui/Ui.js';
import { WordManager } from '../systems/WordManager.js';
import { CivilianManager } from '../systems/CivilianManager.js';
import { PowerupManager } from '../systems/PowerupManager.js';
import { RNG, normalizeText } from '../systems/Utils.js';
import { BOSSES } from '../data/bosses.js';
const LETTERS='abcdefghijklmnñopqrstuvwxyz'.split('');
export class GameScene extends Phaser.Scene{constructor(){super('GameScene')} create(){this.run=this.save.activeRun; if(!this.run){this.scene.start('MenuScene');return;} this.node=this.run.nodes[this.run.nodeIndex]; this.rng=new RNG(this.run.seed+'-'+this.run.nodeIndex); this.wordManager=new WordManager(this.save,this.rng); this.civManager=new CivilianManager(this.save,this.rng); this.powerups=new PowerupManager(this.save,this.rng); const act=this.runManager.actFor(this.run,this.run.nodeIndex); const categoryKey=this.run.categoryKey==='loteria'?this.rng.pick(['jardineria','matematicas','ciencia','floristeria','fantasia','zombia','libreria','zoologia','quimica','fisica','ecologia']):this.run.categoryKey; this.word=this.wordManager.pickWord({categoryKey,difficulty:this.run.difficulty,act}); this.boss=this.node.type==='boss'?this.runManager.bossFor(this.run):null; this.civ=this.civManager.pick({categoryKey,node:this.run.nodeIndex+1,boss:!!this.boss,difficulty:this.run.difficulty}); this.civManager.markSeen(this.civ); this.maxFails=7; this.fails=0; if(this.run.freeHeal){this.maxFails++; this.run.freeHeal--;} this.used=new Set(); this.revealed=new Set(); this.hintLevel=this.run.difficulty==='hard'?0:1; if(this.run.powerups?.some(p=>p.type==='extra_start_hint')) this.hintLevel=Math.min(2,this.hintLevel+1); this.freeEmergency=false; this.emergencyUsed=false; this.consecutiveFails=0; this.hintsBought=0; this.perfectClean=true; this.draw(); }
 draw(){bg(this); title(this,this.boss?`BOSS: ${this.boss.name}`:'Rescate Civilian',`${this.word.categoria} · ${this.word.subcategoria}`); const w=this.scale.width,h=this.scale.height; this.add.text(42,96,`Nodo ${this.run.nodeIndex+1}/${this.run.total} · ${this.run.difficulty==='hard'?'Difícil':'Normal'} ${this.boss?'· '+this.boss.rule:''}`,{fontSize:'14px',color:'#ffdf7e'}); this.civGroup=this.add.group(); this.drawCivilian(); this.wordGroup=this.add.group(); this.drawWord(); this.msg=this.add.text(w/2,382,this.currentHintText(),{fontSize:'17px',align:'center',color:'#eaf7ff',wordWrap:{width:w-130}}).setOrigin(.5); this.status=this.add.text(w/2,438,'K-IA espera tu letra.',{fontSize:'20px',fontStyle:'700',color:'#7df9ff'}).setOrigin(.5); this.drawKeyboard(); button(this,105,h-38,160,42,'Pista +1 fallo',()=>this.buyHint(),{size:'14px',stroke:0xffe14a}); button(this,w-105,h-38,160,42,'Pausa / menú',()=>{this.storage.save(this.save); this.scene.start('MenuScene')},{size:'14px'}); this.input.keyboard.on('keydown',e=>{const k=e.key.toLowerCase(); if(LETTERS.includes(k)) this.guess(k);}); }
 drawCivilian(){const x=128,y=232; const col=Phaser.Display.Color.HexStringToColor(this.civ.color||'#31f7ff').color; this.add.text(x,118,this.civ.name,{fontSize:'16px',fontStyle:'800',color:'#eaf7ff'}).setOrigin(.5); this.add.text(x,140,`${this.civ.rarity.toUpperCase()} · ${this.civ.family}`,{fontSize:'11px',color:'#7df9ff'}).setOrigin(.5); this.add.circle(x,y-42,30,col,.25).setStrokeStyle(3,col); this.add.rectangle(x,y+15,48,78,col,.18).setStrokeStyle(3,col); this.add.circle(x-12,y-48,4,0xffffff); this.add.circle(x+12,y-48,4,0xffffff); this.lifeBarBg=this.add.rectangle(x,y+78,110,12,0x330b16).setStrokeStyle(1,0xff5470); this.lifeBar=this.add.rectangle(x-55,y+78,110,12,0xff3d5f).setOrigin(0,.5); this.lifeText=this.add.text(x,y+100,`VIDA ${this.maxFails-this.fails}/${this.maxFails}`,{fontSize:'14px',color:'#ffb3c0'}).setOrigin(.5); }
 updateLife(){const remain=Math.max(0,this.maxFails-this.fails); this.lifeBar.width=110*(remain/this.maxFails); this.lifeText.setText(`VIDA ${remain}/${this.maxFails}`); }
 drawWord(){const chars=this.word.solucion.split(''); const w=this.scale.width; const clean=chars.filter(c=>c!==' ').length; const size=clean>18?28:clean>12?34:42; let x=w/2-(Math.min(chars.length,18)*size)/2, y=190; chars.forEach((ch,i)=>{ if(i>0 && i%18===0){y+=52; x=w/2-(Math.min(chars.length-i,18)*size)/2;} if(ch===' '){x+=size*.7; return;} const shown=this.revealed.has(ch)||/\d/.test(ch); const rect=this.add.rectangle(x,y,size-5,42,shown?0x173d35:0x101b3d,.95).setStrokeStyle(2,shown?0x39ff88:0x31f7ff); const txt=this.add.text(x,y,shown?this.displayChar(ch):'?',{fontSize:'24px',fontStyle:'900',color:shown?'#b6ffd5':'#7df9ff'}).setOrigin(.5); this.wordGroup.addMultiple([rect,txt]); x+=size; }); }
 redrawWord(){this.wordGroup.clear(true,true); this.drawWord();}
 displayChar(ch){ const original=this.word.mostrarComo.toLowerCase(); return ch.toUpperCase(); }
 currentHintText(){ const k='pista'+this.hintLevel; return `PISTA ${this.hintLevel}: ${this.word[k]||this.word.pista4}`; }
 drawKeyboard(){this.keyButtons={}; const w=this.scale.width; const startX=w/2-390, startY=475; LETTERS.forEach((l,i)=>{const x=startX+(i%10)*86,y=startY+Math.floor(i/10)*48; const b=button(this,x,y,70,38,l.toUpperCase(),()=>this.guess(l),{size:'18px'}); this.keyButtons[l]=b;}); }
 setKey(l,good){const b=this.keyButtons[l]; if(!b)return; b.r.disableInteractive(); b.r.setFillStyle(good?0x174d35:0x451122); b.t.setColor(good?'#86ffb2':'#ff8aa0');}
 guess(l){ if(this.used.has(l)||this.fails>=this.maxFails)return; this.used.add(l); this.save.stats.letters[l]=(this.save.stats.letters[l]||0)+1; const sol=this.word.solucion; if(sol.includes(l)){ this.revealed.add(l); this.setKey(l,true); this.status.setText('¡Letra encontrada! Civilian resiste.'); this.sounder.play('ok'); this.consecutiveFails=0; if(this.powerups.has(this.run,'echo')&&this.rng.next()<.25) this.revealRandom(); this.redrawWord(); if(this.isComplete()) this.win(); } else { this.setKey(l,false); this.applyFail('Esa letra no está. Civilian recibe daño.'); }}
 applyFail(msg){ if(this.powerups.consumeType(this.run,'shield')){this.status.setText('Blindaje Civilian absorbe el daño.'); this.sounder.play('ok'); return;} this.fails++; this.perfectClean=false; this.consecutiveFails++; this.updateLife(); this.sounder.play('hurt'); if(this.save.settings.blood) this.redSplash(); this.status.setText(msg); if(this.run.difficulty==='normal'&&!this.emergencyUsed&&(this.consecutiveFails>=3||this.maxFails-this.fails===1)){this.freeEmergency=true; this.emergencyUsed=true; this.status.setText('PISTA DE EMERGENCIA DISPONIBLE.');} if(this.fails>=this.maxFails) this.lose(); }
 redSplash(){for(let i=0;i<12;i++){const c=this.add.circle(128+Phaser.Math.Between(-70,70),235+Phaser.Math.Between(-70,80),Phaser.Math.Between(2,7),0xff1538,.75); this.tweens.add({targets:c,alpha:0,y:'+=30',duration:650,onComplete:()=>c.destroy()});}}
 buyHint(){ if(this.hintLevel>=4){this.status.setText('K-IA no tiene más datos que filtrar.'); return;} let free=false; if(this.freeEmergency){free=true; this.freeEmergency=false;} if(this.run.freeHints){free=true; this.run.freeHints--;} if(this.powerups.consumeType(this.run,'free_hint')) free=true; if(!free){this.hintsBought++; this.save.stats.hintsBought++; this.applyFail('La pista tiene precio. +1 fallo.'); if(this.fails>=this.maxFails) return;} this.hintLevel++; this.msg.setText(this.currentHintText()); this.status.setText(free?'Pista gratis filtrada por K-IA.':'Pista comprada. Información recuperada.'); this.sounder.play('loot'); }
 revealRandom(){const letters=[...new Set(this.word.solucion.replace(/ /g,'').split(''))].filter(l=>!this.revealed.has(l)); if(letters.length){this.revealed.add(this.rng.pick(letters)); this.redrawWord();}}
 isComplete(){return this.word.solucion.split('').every(ch=>ch===' '||this.revealed.has(ch)||/\d/.test(ch));}
 win(){this.sounder.play('win'); const perfect=this.fails===0; const critical=this.maxFails-this.fails===1; this.civManager.markSaved(this.civ,{perfect,critical,difficulty:this.run.difficulty,wordId:this.word.id,word:this.word.mostrarComo}); this.save.codex[this.word.id]={id:this.word.id,solucion:this.word.solucion,mostrarComo:this.word.mostrarComo,categoria:this.word.categoria,categoryKey:this.word.categoryKey,subcategoria:this.word.subcategoria,dificultad:this.word.dificultad,times:(this.save.codex[this.word.id]?.times||0)+1,perfect:(this.save.codex[this.word.id]?.perfect||false)||perfect,last:new Date().toISOString(),pistaFinal:this.word.pista4}; this.save.stats.civiliansSaved++; this.save.stats.currentStreak++; this.save.stats.bestStreak=Math.max(this.save.stats.bestStreak,this.save.stats.currentStreak); this.run.saved++; this.run.datos+=30+(perfect?20:0)+(critical?15:0)+(this.run.difficulty==='hard'?20:0); this.run.lastResult={win:true,perfect,critical,civ:this.civ,word:this.word,hints:this.hintsBought,fails:this.fails}; if(this.boss){this.save.stats.bossesDefeated++; this.run.bosses.push(this.boss.name);} this.storage.save(this.save); this.scene.start('RewardScene'); }
 lose(){this.sounder.play('lose'); this.civManager.markLost(this.civ); this.save.stats.civiliansLost++; this.save.stats.currentStreak=0; this.run.lost++; this.run.lastResult={win:false,civ:this.civ,word:this.word,hints:this.hintsBought,fails:this.fails}; this.storage.save(this.save); this.scene.start('RewardScene'); }
}
