import { bg,title,button,back } from '../ui/Ui.js';
import { CIVILIANS } from '../data/civilians.js';
import { ACHIEVEMENTS } from '../data/achievements.js';
import { POWERUPS } from '../data/powerups.js';
import { pct } from '../systems/Utils.js';
class ScrollScene extends Phaser.Scene{makeWheel(group){this.input.on('wheel',(p,go,dx,dy)=>{group.y=Phaser.Math.Clamp(group.y-dy*.45,-Math.max(0,group.height-this.scale.height+140),0);});}}
export class CollectionScene extends ScrollScene{constructor(){super('CollectionScene')} create(){bg(this); title(this,'Civilians','Archivo de rescate'); back(this); const g=this.add.container(55,115); let y=0; CIVILIANS.forEach((c,i)=>{const saved=this.save.collection[c.id]?.saved; const seen=this.save.collection[c.id]?.seen; const color=Phaser.Display.Color.HexStringToColor(c.color).color; g.add(this.add.rectangle(180+(i%3)*235,y+32,215,54,saved?0x123424:seen?0x30141f:0x101b3d,.92).setStrokeStyle(1,color)); g.add(this.add.text(85+(i%3)*235,y+13,`${saved?'✓':seen?'?':'🔒'} ${c.name}\n${c.rarity} · ${c.family}`,{fontSize:'12px',color:saved?'#b6ffd5':'#a9c8ff'})); if(i%3===2)y+=64;}); g.height=y+100; this.makeWheel(g);}}
export class CodexScene extends ScrollScene{constructor(){super('CodexScene')} create(){bg(this); title(this,'Codex IA','Datos robados a K-IA'); back(this); const entries=Object.values(this.save.codex); const g=this.add.container(70,120); let y=0; if(!entries.length) g.add(this.add.text(0,0,'Aún no has recuperado Datos IA.',{fontSize:'20px',color:'#ffdf7e'})); entries.sort((a,b)=>a.categoria.localeCompare(b.categoria)).forEach((e,i)=>{g.add(this.add.rectangle(360,y+48,660,84,0x08122b,.92).setStrokeStyle(1,0x31f7ff)); g.add(this.add.text(45,y+12,`DATO IA RECUPERADO · ${e.mostrarComo.toUpperCase()}\n${e.categoria} · ${e.subcategoria} · Veces: ${e.times}\n${e.pistaFinal}`,{fontSize:'14px',color:'#eaf7ff',wordWrap:{width:620}})); y+=96;}); g.height=y+100; this.makeWheel(g);}}
export class AchievementsScene extends ScrollScene{constructor(){super('AchievementsScene')} create(){bg(this); title(this,'Logros','Insignias de neón'); back(this); const g=this.add.container(70,120); let y=0; ACHIEVEMENTS.forEach((a,i)=>{const u=this.save.achievements[a.id]; g.add(this.add.rectangle(360,y+35,660,62,u?0x173d35:0x101b3d,.92).setStrokeStyle(1,u?0x39ff88:0x31f7ff)); g.add(this.add.text(45,y+10,`${u?'🏆':'🔒'} ${a.secret&&!u?'Logro secreto':a.title}\n${a.secret&&!u?'???':a.description}`,{fontSize:'14px',color:u?'#b6ffd5':'#a9c8ff'})); y+=72;}); g.height=y+100; this.makeWheel(g);}}
export class ProgressScene extends Phaser.Scene{constructor(){super('ProgressScene')} create(){bg(this); title(this,'Progreso','Perfil de rescatador'); back(this); const s=this.save.stats; const civ=Object.values(this.save.collection).filter(c=>c.saved).length; const cod=Object.keys(this.save.codex).length; const ach=Object.keys(this.save.achievements).length; this.add.text(this.scale.width/2,130,`Título activo: ${this.save.titles.active}\nRuns iniciadas: ${s.runsStarted}\nRuns completadas: ${s.runsCompleted}\nCivilians salvados: ${s.civiliansSaved}\nCivilians perdidos: ${s.civiliansLost}\nMejor racha: ${s.bestStreak}\nDatos IA del Codex: ${cod}\nDatos IA disponibles: ${this.save.economy?.datosIA||0}\nCivilians comprados: ${this.save.economy?.civiliansBought||0}\nCivilians únicos: ${civ}/60\nLogros: ${ach}/${ACHIEVEMENTS.length}\nBosses derrotados: ${s.bossesDefeated}\nPistas compradas: ${s.hintsBought}\nRun diaria completadas: ${s.dailyCompleted}`,{fontSize:'22px',align:'center',color:'#eaf7ff',lineSpacing:7}).setOrigin(.5,0); }}
export class PowerupsScene extends ScrollScene{constructor(){super('PowerupsScene')} create(){bg(this); title(this,'Powerups','Arsenal contra K-IA'); back(this); const g=this.add.container(70,120); let y=0; POWERUPS.forEach((p,i)=>{const d=this.save.discoveredPowerups[p.id]; g.add(this.add.rectangle(360,y+35,660,62,d?0x173d35:0x101b3d,.92).setStrokeStyle(1,d?0x39ff88:0x31f7ff)); g.add(this.add.text(45,y+10,`${d?'⚡':'🔒'} ${p.name} · ${p.rarity}\n${d?p.description:'Descúbrelo durante una run.'}`,{fontSize:'14px',color:d?'#b6ffd5':'#a9c8ff'})); y+=72;}); g.height=y+100; this.makeWheel(g);}}
