import { AI_RIVALS, FIRST_NAMES, LAST_NAMES, NICKS } from '../data/aiRivals.js';
export class AIManager{
 static listByDifficulty(diff){return AI_RIVALS.filter(r=>r.difficulty===diff || (diff==='hard'&&r.difficulty==='legendary') || diff==='mixed');}
 static randomRival(diff='normal'){let pool=AI_RIVALS.filter(r=>diff==='mixed'||r.difficulty===diff); if(!pool.length)pool=AI_RIVALS; return Phaser.Utils.Array.GetRandom(pool);}
 static generateRival(diff='normal'){return {id:`gen_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,name:Phaser.Utils.Array.GetRandom(FIRST_NAMES),surname:Phaser.Utils.Array.GetRandom(LAST_NAMES),nick:Phaser.Utils.Array.GetRandom(NICKS),difficulty:diff,rarity:diff==='hard'?'Épico':diff==='normal'?'Raro':'Común',style:'Generado',quote:'He venido a ensuciar tu cuadro.'};}
 static fullName(r){return `${r.name} “${r.nick}” ${r.surname}`;}
 static weights(diff,state='tied',streak=0,lead=0,passives=[]){const tbl={easy:{leading:[1,4,3,92],tied:[2,5,4,89],losing:[3,7,5,85]},normal:{leading:[3,7,5,85],tied:[4,9,7,80],losing:[5,11,9,75]},hard:{leading:[4,9,7,80],tied:[5,11,9,75],losing:[7,14,11,68]},legendary:{leading:[5,11,9,75],tied:[6,13,10,71],losing:[8,16,13,63]}}; let [direct,penalty,free,miss]=tbl[diff]?.[state]||tbl.normal.tied; let mult=1-Math.min(.45,streak*.1); if(lead>=3)mult*=.75; if(lead<=-2)mult*=1.15; if(passives.includes('antistreak') && streak>=2)mult*=.78; direct*=mult;penalty*=mult;free*=mult; const sum=direct+penalty+free+miss; return {direct:direct/sum,penalty:penalty/sum,free:free/sum,miss:miss/sum};}
 static rollCentisecond(diff,aiScore,humanScore,streak=0,passives=[]){let state= aiScore>humanScore?'leading':aiScore<humanScore?'losing':'tied'; const w=this.weights(diff,state,streak,aiScore-humanScore,passives); const r=Math.random(); if(r<w.direct)return 0; if(r<w.direct+w.penalty)return Phaser.Utils.Array.GetRandom([1,2,3]); if(r<w.direct+w.penalty+w.free)return Phaser.Utils.Array.GetRandom([97,98,99]); let v=Phaser.Math.Between(4,96); if([97,98,99,0,1,2,3].includes(v))v=50; return v;}
 static rollEvenChance(diff,state='tied'){let p={easy:.45,normal:.55,hard:.62,legendary:.68}[diff]||.55; if(state==='leading')p-=.06; if(state==='losing')p+=.05; return Math.random()<p;}
}
