/* ViveroBox Academy - Phaser 3 */
const W=1280,H=720, KEY='viverobox_academy_save_v1';
const C={bg:0x07180f, panel:0x123320, panel2:0x1b4d32, green:0x66f2a0, gold:0xffd166, red:0xff5d73, blue:0x55c7ff, purple:0xb46cff, text:'#eafff1'};
const BOXES=[
 {id:'semillero',name:'Caja Semillero',price:50,desc:'Plantas básicas, aromáticas y semilleros'},
 {id:'herramientas',name:'Caja Herramientas',price:50,desc:'Herramientas de mano y objetos de trabajo'},
 {id:'vivero',name:'Caja Vivero',price:75,desc:'Árboles, arbustos y plantas ornamentales'},
 {id:'florista',name:'Caja Florista',price:75,desc:'Flor cortada y materiales de floristería'},
 {id:'maquinaria',name:'Caja Maquinaria',price:100,desc:'Maquinaria y equipo avanzado'},
 {id:'profesional',name:'Caja Profesional',price:100,desc:'Mezcla premium de jardinería y floristería'}
];
function deepClone(o){return JSON.parse(JSON.stringify(o));}
function shuffle(a){const b=[...a]; for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [b[i],b[j]]=[b[j],b[i]];} return b;}
function getSave(){
 let s; try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}
 if(!s){s={playerName:'Gamer',coins:100,secretKeys:0,nurseryTokens:0,arcaneDust:0,ownedCollectibles:[],ownedSecretCollectibles:[],ownedEpis:['guantes_trabajo'],equippedEpis:{},questionQueue:[],correctAnswers:0,wrongAnswers:0,totalAnswered:0,perfectRounds:0,duplicateWins:0,openedBoxes:{},secretUnlocked:false,achievements:[],settings:{sound:true,music:false}};}
 return s;
}
function setSave(s){localStorage.setItem(KEY,JSON.stringify(s));}
function itemById(id){return window.VIVEROBOX_COLLECTIBLES.find(x=>x.id===id)}
function secById(id){return window.VIVEROBOX_SECRET_COLLECTIBLES.find(x=>x.id===id)}
class GameScene extends Phaser.Scene{
 constructor(){super('GameScene'); this.state='menu';}
 create(){this.save=getSave(); this.audioCtx=null; this.input.keyboard.on('keydown-ESC',()=>this.goBack()); this.showMenu();}
 saveNow(){setSave(this.save)}
 clear(){this.children.removeAll(); document.querySelectorAll('.viverobox-name-input').forEach(x=>x.remove());}
 sound(type='click'){
  if(!this.save.settings.sound) return;
  try{ if(!this.audioCtx) this.audioCtx=new (window.AudioContext||window.webkitAudioContext)(); const ctx=this.audioCtx; const o=ctx.createOscillator(), g=ctx.createGain(); o.connect(g); g.connect(ctx.destination); const map={click:420,good:740,bad:140,coin:920,box:240,secret:110,magic:520}; o.frequency.value=map[type]||440; o.type=type==='secret'?'sawtooth':'sine'; g.gain.setValueAtTime(.001,ctx.currentTime); g.gain.exponentialRampToValueAtTime(.08,ctx.currentTime+.02); g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18); o.start(); o.stop(ctx.currentTime+.2);}catch(e){}
 }
 bg(secret=false){
  this.add.rectangle(W/2,H/2,W,H,secret?0x12071d:C.bg);
  for(let i=0;i<80;i++){let x=Math.random()*W,y=Math.random()*H,c=secret?0x8b4cff:0x41d47a; let p=this.add.circle(x,y,Phaser.Math.Between(1,3),c,.15); this.tweens.add({targets:p,y:y-20,alpha:.02,duration:Phaser.Math.Between(2500,6000),yoyo:true,repeat:-1});}
  this.add.rectangle(W/2,35,W,70,secret?0x210f32:0x0f2a1b,.92).setStrokeStyle(2,secret?0xb46cff:C.green,.5);
  this.txt(25,22,`${this.save.playerName}`,24,C.text).setOrigin(0,0.5);
  this.txt(220,22,`🪙 ${this.save.coins}`,24,'#ffe69a').setOrigin(0,0.5);
  this.txt(360,22,`🗝️ ${this.save.secretKeys}`,24,'#d6c7ff').setOrigin(0,0.5);
  if(this.state.includes('shop')||this.state.includes('box')) this.txt(505,22,`🎟️ ${this.save.nurseryTokens}`,24,'#baf7cb').setOrigin(0,0.5);
  if(secret||this.state.includes('secret')) this.txt(650,22,`✦ ${this.save.arcaneDust}`,24,'#dcb8ff').setOrigin(0,0.5);
 }
 txt(x,y,t,s=24,color=C.text,align='left'){return this.add.text(x,y,t,{fontFamily:'Arial, sans-serif',fontSize:s+'px',color,align,wordWrap:{width:1100}})}
 panel(x,y,w,h,color=C.panel,alpha=.9){return this.add.rectangle(x,y,w,h,color,alpha).setStrokeStyle(2,C.green,.45)}
 btn(x,y,w,h,label,cb,opt={}){let color=opt.color||C.panel2; const r=this.add.rectangle(x,y,w,h,color,.95).setStrokeStyle(2,opt.stroke||C.green,.8).setInteractive({useHandCursor:true}); const t=this.txt(x,y,label,opt.size||24,opt.textColor||C.text,'center').setOrigin(.5); r.on('pointerover',()=>r.setScale(1.03)); r.on('pointerout',()=>r.setScale(1)); r.on('pointerdown',()=>{this.sound('click'); cb&&cb();}); return {r,t};}
 back(){this.btn(1135,675,210,48,'← Atrás',()=>this.goBack(),{color:0x244131});}
 goBack(){const map={quiz:'menu',duplicate:'menu',boxes:'menu',boxopen:'boxes',collection:'menu',nursery:'collection',storage:'collection',florist:'collection',shop:'boxes',epi:'menu',epichallenge:'epi',secret:'menu',secretshop:'secret',achievements:'menu',options:'menu'}; this['show'+(map[this.state]||'Menu').replace(/^./,m=>m.toUpperCase())]?.() || this.showMenu();}
 showMenu(){this.state='menu'; this.clear(); this.bg(); this.txt(W/2,105,'🌿 ViveroBox Academy',52,'#baffcf','center').setOrigin(.5); this.txt(W/2,155,'Jardinería · Floristería · Colección · EPIs',24,'#d9ffe6','center').setOrigin(.5); this.drawPlant(175,300,1.5,'arbol'); this.drawAvatar(1040,330,1.25); const buttons=[['Ganar monedas',()=>this.showQuiz()],['Duplicar monedas',()=>this.showDuplicate()],['Abrir cajas',()=>this.showBoxes()],['Colección',()=>this.showCollection()],['Taquilla EPIs',()=>this.showEpi()],['Invernadero Prohibido',()=>this.showSecret()],['Logros / Progreso',()=>this.showAchievements()],['Opciones',()=>this.showOptions()]]; buttons.forEach((b,i)=>this.btn(420+(i%2)*260,250+Math.floor(i/2)*82,235,58,b[0],b[1],{color:i===5?0x3b185a:0x1d5c39,stroke:i===5?C.purple:C.green})); this.txt(W/2,640,'Completa rondas, abre cajas de 2 objetos y equipa a Gamer con EPIs correctos.',21,'#c6ffd7','center').setOrigin(.5);}
 ensureQueue(){if(!this.save.questionQueue||this.save.questionQueue.length===0){this.save.questionQueue=shuffle(window.VIVEROBOX_QUESTIONS.map(q=>q.id)); this.saveNow();}}
 nextQuestion(){this.ensureQueue(); const id=this.save.questionQueue.shift(); this.saveNow(); return window.VIVEROBOX_QUESTIONS.find(q=>q.id===id);}
 showQuiz(){this.state='quiz'; this.quiz={i:0,earned:0,mode:'normal',rewards:[10,15,20,25,30]}; this.ask();}
 ask(){this.clear(); this.bg(); const q=this.nextQuestion(); this.currentQ=q; this.panel(W/2,145,1080,115); this.txt(W/2,105,`Pregunta ${this.quiz.i+1}/5 · Premio: ${this.quiz.rewards[this.quiz.i]} monedas`,27,'#ffe69a','center').setOrigin(.5); this.txt(W/2,145,q.question,25,C.text,'center').setOrigin(.5); q.options.forEach((op,i)=>this.btn(W/2,255+i*78,930,58,op,()=>this.answer(i),{color:0x163d29,size:22})); this.btn(110,675,180,48,'Abandonar',()=>{this.save.coins+=this.quiz.earned; this.saveNow(); this.showMenu();},{color:0x503030,stroke:C.red}); this.txt(W/2,620,`Ganado en esta ronda: ${this.quiz.earned} monedas`,23,'#baffcf','center').setOrigin(.5);}
 answer(i){const q=this.currentQ, ok=i===q.answer; this.save.totalAnswered++; if(ok){this.save.correctAnswers++; this.quiz.earned+=this.quiz.rewards[this.quiz.i]; this.sound('good');} else {this.save.wrongAnswers++; this.sound('bad');}
 this.clear(); this.bg(); this.panel(W/2,225,1000,300,ok?0x174328:0x48202a); this.txt(W/2,130,ok?'✅ ¡Correcto!':'❌ Ronda terminada',42,ok?'#baffcf':'#ffb0bd','center').setOrigin(.5); this.txt(W/2,205,`Respuesta correcta: ${q.options[q.answer]}`,24,'#ffe69a','center').setOrigin(.5); this.txt(W/2,275,q.explanation,23,C.text,'center').setOrigin(.5); if(ok && this.quiz.i<4){this.btn(W/2,430,260,58,'Siguiente',()=>{this.quiz.i++; this.ask();},{color:0x1f6a3f});} else { if(ok && this.quiz.i===4){this.save.perfectRounds++; this.save.secretKeys++; this.txt(W/2,378,'Ronda perfecta: +100 monedas y +1 llave secreta',27,'#d6c7ff','center').setOrigin(.5);} this.save.coins+=this.quiz.earned; this.saveNow(); this.btn(W/2,455,300,58,'Volver al menú',()=>this.showMenu(),{color:0x1f6a3f});}}
 showDuplicate(){this.state='duplicate'; this.clear(); this.bg(); this.txt(W/2,100,'⚡ Duplicar monedas',45,'#ffe69a','center').setOrigin(.5); this.panel(W/2,270,880,270); this.txt(W/2,210,'Pagas 100 monedas. Si aciertas 3 preguntas seguidas, recibes 200. Si fallas una, pierdes la entrada.',28,C.text,'center').setOrigin(.5); if(this.save.coins<100) this.txt(W/2,315,'Necesitas 100 monedas para jugar.',26,'#ffb0bd','center').setOrigin(.5); else this.btn(W/2,350,260,60,'Jugar',()=>{this.save.coins-=100; this.saveNow(); this.dup={i:0}; this.askDup();},{color:0x5d4a16,stroke:C.gold}); this.back();}
 askDup(){this.state='duplicate'; this.clear(); this.bg(); const q=this.nextQuestion(); this.currentQ=q; this.txt(W/2,95,`Duplicar · Pregunta ${this.dup.i+1}/3`,36,'#ffe69a','center').setOrigin(.5); this.panel(W/2,155,1060,100); this.txt(W/2,155,q.question,24,C.text,'center').setOrigin(.5); q.options.forEach((op,i)=>this.btn(W/2,260+i*78,930,58,op,()=>this.answerDup(i),{color:0x392b17,stroke:C.gold,size:22}));}
 answerDup(i){const q=this.currentQ, ok=i===q.answer; this.save.totalAnswered++; ok?this.save.correctAnswers++:this.save.wrongAnswers++; this.clear(); this.bg(); this.panel(W/2,230,980,280,ok?0x174328:0x48202a); if(ok && this.dup.i<2){this.txt(W/2,155,'✅ Correcto. Sigue la racha.',38,'#baffcf','center').setOrigin(.5); this.txt(W/2,230,q.explanation,23,C.text,'center').setOrigin(.5); this.btn(W/2,390,260,58,'Siguiente',()=>{this.dup.i++; this.askDup();},{color:0x1f6a3f});}
 else if(ok){this.save.coins+=200; this.save.duplicateWins++; this.saveNow(); this.sound('coin'); this.txt(W/2,160,'🏆 ¡Duplicado conseguido!',42,'#ffe69a','center').setOrigin(.5); this.txt(W/2,240,'Has recibido 200 monedas.',30,C.text,'center').setOrigin(.5); this.btn(W/2,390,280,58,'Volver',()=>this.showMenu(),{color:0x1f6a3f});}
 else {this.saveNow(); this.txt(W/2,155,'❌ Duplicar fallido',42,'#ffb0bd','center').setOrigin(.5); this.txt(W/2,225,`Correcta: ${q.options[q.answer]}`,24,'#ffe69a','center').setOrigin(.5); this.txt(W/2,285,q.explanation,23,C.text,'center').setOrigin(.5); this.btn(W/2,430,280,58,'Volver',()=>this.showMenu(),{color:0x503030,stroke:C.red});}}
 showBoxes(){this.state='boxes'; this.clear(); this.bg(); this.txt(W/2,92,'🎁 Abrir cajas',44,'#baffcf','center').setOrigin(.5); BOXES.forEach((b,i)=>{let x=255+(i%3)*390,y=220+Math.floor(i/3)*170; this.panel(x,y,340,120,0x143925); this.txt(x,y-35,b.name,25,'#ffe69a','center').setOrigin(.5); this.txt(x,y,b.desc,18,C.text,'center').setOrigin(.5); this.btn(x,y+45,170,42,`${b.price} 🪙`,()=>this.openBox(b),{color:0x1f6a3f});}); this.btn(500,625,245,50,'Tienda de vivero',()=>this.showShop(),{color:0x1b5b3a}); this.back();}
 poolFor(box){return window.VIVEROBOX_COLLECTIBLES.filter(it=>it.boxes.includes(box.id));}

 pickRewards(pool, ownedIds, openedBefore){
  const missing=pool.filter(it=>!ownedIds.includes(it.id));
  let picks=[];
  if(openedBefore===0 && missing.length) picks.push(shuffle(missing)[0]);
  const rest=shuffle(pool.filter(it=>!picks.some(p=>p.id===it.id)));
  while(picks.length<2 && rest.length) picks.push(rest.shift());
  return picks;
 }
 openBox(box){if(this.save.coins<box.price){this.toast('No tienes monedas suficientes.'); return;} this.lastBox=box; this.save.coins-=box.price; const openedBefore=(this.save.openedBoxes[box.id]||0); this.save.openedBoxes[box.id]=openedBefore+1; const pool=this.poolFor(box); const picks=this.pickRewards(pool,this.save.ownedCollectibles,openedBefore); this.showBoxOpen(box,picks,false);}
 openSecretBox(){if(this.save.secretKeys<3){this.toast('Necesitas 3 llaves secretas.'); return;} this.lastSecret=true; this.save.secretKeys-=3; const openedBefore=(this.save.openedBoxes.secret||0); this.save.openedBoxes.secret=openedBefore+1; const picks=this.pickRewards(window.VIVEROBOX_SECRET_COLLECTIBLES,this.save.ownedSecretCollectibles,openedBefore); this.showBoxOpen({id:'secret',name:'Caja del Invernadero Prohibido'},picks,true);}
 showBoxOpen(box,picks,secret){this.state='boxopen'; this.clear(); this.bg(secret); this.sound(secret?'secret':'box'); this.txt(W/2,88,secret?'🔮 Caja del Invernadero Prohibido':`🎁 ${box.name}`,40,secret?'#dcb8ff':'#ffe69a','center').setOrigin(.5); this.panel(W/2,225,420,210,secret?0x2b1642:0x214d30); let chest=this.add.rectangle(W/2,225,180,110,secret?0x4b236f:0x8b5a2b).setStrokeStyle(4,secret?C.purple:C.gold); this.tweens.add({targets:chest,angle:4,duration:80,yoyo:true,repeat:8,onComplete:()=>this.revealRewards(picks,secret)});}
 revealRewards(picks,secret){let newCount=0, repCount=0; picks.forEach((it,idx)=>{const x=430+idx*420,y=300; const owned=secret?this.save.ownedSecretCollectibles.includes(it.id):this.save.ownedCollectibles.includes(it.id); this.card(x,y,it,secret,owned); if(owned){repCount++; if(secret)this.save.arcaneDust+=5; else this.save.nurseryTokens+=5; this.particles(x,y,secret?C.purple:C.green);} else {newCount++; if(secret)this.save.ownedSecretCollectibles.push(it.id); else this.save.ownedCollectibles.push(it.id); this.particles(x,y,secret?0xdcb8ff:0xffe69a);} }); this.saveNow(); this.txt(W/2,505,newCount?`Nuevos: ${newCount}`:'Sin objetos nuevos',28,newCount?'#baffcf':'#ffcf9a','center').setOrigin(.5); this.txt(W/2,545,repCount?`Repetidos convertidos en +${repCount*5} ${secret?'polvo arcano':'fichas de vivero'}`:'Todos añadidos a la colección',24,secret?'#dcb8ff':'#baffcf','center').setOrigin(.5); this.btn(360,635,220,50,'Abrir otra',()=>secret?this.openSecretBox():this.openBox(this.lastBox||BOXES[0]),{color:secret?0x3b185a:0x1f6a3f}); this.btn(620,635,220,50,secret?'Tienda secreta':'Ir a tienda',()=>secret?this.showSecretShop():this.showShop(),{color:secret?0x3b185a:0x1b5b3a}); this.btn(880,635,220,50,'Volver',()=>secret?this.showSecret():this.showBoxes(),{color:0x244131});}
 card(x,y,it,secret,owned){this.add.rectangle(x,y,300,255,secret?0x1f0d30:0x102d1d,.96).setStrokeStyle(3,owned?0xff8f9d:(secret?C.purple:C.gold)); this.drawIcon(x,y-25,it,secret); this.txt(x,y+72,it.name,25,secret?'#dcb8ff':'#ffe69a','center').setOrigin(.5); this.txt(x,y+108,owned?'REPETIDO':(secret?'SECRETO NUEVO':'NUEVO'),23,owned?'#ffb0bd':'#baffcf','center').setOrigin(.5);}
 showCollection(){this.state='collection'; this.clear(); this.bg(); const total=window.VIVEROBOX_COLLECTIBLES.length; this.txt(W/2,90,`📚 Colección normal ${this.save.ownedCollectibles.length}/${total}`,42,'#baffcf','center').setOrigin(.5); this.btn(330,220,280,75,'Vivero',()=>this.showNursery(),{color:0x1f6a3f}); this.btn(650,220,280,75,'Almacén',()=>this.showStorage(),{color:0x1f6a3f}); this.btn(970,220,280,75,'Taller florista',()=>this.showFlorist(),{color:0x1f6a3f}); this.txt(W/2,360,'Las siluetas vacías muestran objetos aún no conseguidos. Pulsa una zona para ver tu progreso.',24,C.text,'center').setOrigin(.5); this.back();}
 showNursery(){this.state='nursery'; this.clear(); this.bg(); this.txt(W/2,80,'🌳 Vivero',42,'#baffcf','center').setOrigin(.5); this.showGrid(window.VIVEROBOX_COLLECTIBLES.filter(i=>i.type==='planta'),120); this.back();}
 showStorage(){this.state='storage'; this.clear(); this.bg(); this.txt(W/2,80,'🧰 Almacén',42,'#baffcf','center').setOrigin(.5); this.showGrid(window.VIVEROBOX_COLLECTIBLES.filter(i=>['herramienta','maquinaria','decoracion'].includes(i.type)),120); this.back();}
 showFlorist(){this.state='florist'; this.clear(); this.bg(); this.txt(W/2,80,'💐 Taller de floristería',42,'#baffcf','center').setOrigin(.5); this.showGrid(window.VIVEROBOX_COLLECTIBLES.filter(i=>i.type==='floristeria'),120); this.back();}
 showGrid(arr,y0){arr.forEach((it,i)=>{let x=105+(i%8)*150,y=y0+Math.floor(i/8)*110; const owned=this.save.ownedCollectibles.includes(it.id); this.add.rectangle(x,y,130,90,owned?0x174328:0x1b1f1d,.9).setStrokeStyle(2,owned?C.green:0x59665e,.55); this.drawIcon(x,y-10,it,false,owned); this.txt(x,y+34,owned?it.name:'???',15,owned?'#eafff1':'#7d8b82','center').setOrigin(.5);});}
 showShop(){this.state='shop'; this.clear(); this.bg(); this.txt(W/2,80,`🎟️ Tienda de vivero · Fichas: ${this.save.nurseryTokens}`,38,'#baffcf','center').setOrigin(.5); const missing=window.VIVEROBOX_COLLECTIBLES.filter(i=>!this.save.ownedCollectibles.includes(i.id)); this.shopGrid(missing,false); this.back();}
 showSecretShop(){this.state='secretshop'; this.clear(); this.bg(true); this.txt(W/2,80,`✦ Tienda secreta · Polvo arcano: ${this.save.arcaneDust}`,38,'#dcb8ff','center').setOrigin(.5); const missing=window.VIVEROBOX_SECRET_COLLECTIBLES.filter(i=>!this.save.ownedSecretCollectibles.includes(i.id)); this.shopGrid(missing,true); this.back();}
 shopGrid(arr,secret){arr.slice(0,32).forEach((it,i)=>{let x=120+(i%8)*145,y=145+Math.floor(i/8)*115; this.add.rectangle(x,y,130,95,secret?0x251039:0x153723,.95).setStrokeStyle(2,secret?C.purple:C.green,.65); this.drawIcon(x,y-15,it,secret,true); this.txt(x,y+25,it.name,14,secret?'#dcb8ff':'#eafff1','center').setOrigin(.5); this.btn(x,y+55,92,28,'10',()=>this.buyItem(it,secret),{size:16,color:secret?0x3b185a:0x1f6a3f,stroke:secret?C.purple:C.green});}); if(!arr.length)this.txt(W/2,300,'¡Tienda completada! Ya tienes todos los objetos.',28,C.text,'center').setOrigin(.5);}
 buyItem(it,secret){if(secret){if(this.save.arcaneDust<10)return this.toast('Necesitas 10 polvo arcano.'); this.save.arcaneDust-=10; this.save.ownedSecretCollectibles.push(it.id); this.sound('magic'); this.saveNow(); this.showSecretShop();} else {if(this.save.nurseryTokens<10)return this.toast('Necesitas 10 fichas de vivero.'); this.save.nurseryTokens-=10; this.save.ownedCollectibles.push(it.id); this.sound('coin'); this.saveNow(); this.showShop();}}
 showEpi(){this.state='epi'; this.clear(); this.bg(); this.txt(W/2,80,`🦺 Taquilla de seguridad de ${this.save.playerName}`,38,'#baffcf','center').setOrigin(.5); this.drawAvatar(330,385,1.7); window.VIVEROBOX_EPIS.forEach((e,i)=>{const owned=this.save.ownedEpis.includes(e.id); const eq=Object.values(this.save.equippedEpis).includes(e.id); let x=650+(i%2)*260,y=155+Math.floor(i/2)*70; this.btn(x,y,235,45,(owned?(eq?'✓ ':''):'🔒 ')+e.name,()=>owned&&this.toggleEpi(e),{size:17,color:eq?0x3d6b2a:0x183624,stroke:owned?C.green:0x666666});}); this.btn(330,610,240,50,'Retos de seguridad',()=>this.showEpichallenge(),{color:0x1f6a3f}); this.btn(610,610,200,50,'Quitar todo',()=>{this.save.equippedEpis={}; this.saveNow(); this.showEpi();},{color:0x503030,stroke:C.red}); this.back();}
 toggleEpi(e){if(this.save.equippedEpis[e.slot]===e.id) delete this.save.equippedEpis[e.slot]; else this.save.equippedEpis[e.slot]=e.id; this.saveNow(); this.showEpi();}
 showEpichallenge(){this.state='epichallenge'; this.clear(); this.bg(); this.txt(W/2,75,'🦺 Retos de seguridad',40,'#baffcf','center').setOrigin(.5); window.VIVEROBOX_EPI_CHALLENGES.forEach((ch,i)=>{let x=235+(i%3)*410,y=150+Math.floor(i/3)*105; this.panel(x,y,360,78); this.txt(x,y-18,ch.title,19,'#ffe69a','center').setOrigin(.5); this.btn(x,y+22,160,34,'Comprobar',()=>this.checkChallenge(ch),{size:16,color:0x1f6a3f});}); this.txt(W/2,620,'Equipa EPIs en la taquilla y comprueba aquí cada tarea. Los retos desbloquean nuevos EPIs.',22,C.text,'center').setOrigin(.5); this.back();}
 checkChallenge(ch){const equipped=Object.values(this.save.equippedEpis); let missing=ch.required.filter(r=>!equipped.includes(r)); (ch.alternativeAny||[]).forEach(group=>{if(!group.some(g=>equipped.includes(g))) missing.push(group.join(' o '));}); this.clear(); this.bg(); this.panel(W/2,250,1000,310,missing.length?0x48202a:0x174328); this.txt(W/2,125,ch.title,38,'#ffe69a','center').setOrigin(.5); this.txt(W/2,185,ch.text,23,C.text,'center').setOrigin(.5); if(missing.length){this.txt(W/2,260,'Faltan EPIs obligatorios: '+missing.join(', '),24,'#ffb0bd','center').setOrigin(.5); this.txt(W/2,320,'No pierdes monedas. Ajusta el equipo y vuelve a intentarlo.',22,C.text,'center').setOrigin(.5);} else {let perfect=(ch.recommended||[]).every(r=>equipped.includes(r)); let reward=perfect?50:30; this.save.coins+=reward; if(!this.save.ownedEpis.includes(ch.unlock))this.save.ownedEpis.push(ch.unlock); this.saveNow(); this.txt(W/2,260,`Equipo correcto. +${reward} monedas`,28,'#baffcf','center').setOrigin(.5); this.txt(W/2,320,`EPI desbloqueado: ${window.VIVEROBOX_EPIS.find(e=>e.id===ch.unlock).name}`,24,'#ffe69a','center').setOrigin(.5);} this.btn(W/2,470,260,55,'Volver a retos',()=>this.showEpichallenge(),{color:0x1f6a3f});}
 showSecret(){this.state='secret'; this.clear(); this.bg(true); this.txt(W/2,80,'🔮 Invernadero Prohibido',43,'#dcb8ff','center').setOrigin(.5); if(!this.save.secretUnlocked && this.save.secretKeys<3){this.txt(W/2,180,'Una puerta oculta espera 3 llaves secretas...',30,'#dcb8ff','center').setOrigin(.5);} else {this.save.secretUnlocked=true; this.saveNow(); this.btn(W/2,150,330,58,'Abrir caja secreta · 3 🗝️',()=>this.openSecretBox(),{color:0x3b185a,stroke:C.purple}); this.btn(W/2,220,270,50,'Tienda secreta',()=>this.showSecretShop(),{color:0x3b185a,stroke:C.purple}); this.txt(W/2,295,`Colección secreta: ${this.save.ownedSecretCollectibles.length}/${window.VIVEROBOX_SECRET_COLLECTIBLES.length}`,26,'#dcb8ff','center').setOrigin(.5); this.showSecretGrid();} this.back();}
 showSecretGrid(){window.VIVEROBOX_SECRET_COLLECTIBLES.slice(0,40).forEach((it,i)=>{let x=90+(i%10)*120,y=360+Math.floor(i/10)*75; const owned=this.save.ownedSecretCollectibles.includes(it.id); this.add.circle(x,y,28,owned?0x5b2585:0x16101f,.95).setStrokeStyle(2,owned?C.purple:0x51445c); this.txt(x,y,owned?'✦':'?',20,owned?'#dcb8ff':'#777','center').setOrigin(.5);});}
 showAchievements(){this.state='achievements'; this.clear(); this.bg(); this.txt(W/2,80,'🏆 Logros y progreso',42,'#baffcf','center').setOrigin(.5); const lines=[`Preguntas respondidas: ${this.save.totalAnswered}/1000`, `Aciertos: ${this.save.correctAnswers}`, `Fallos: ${this.save.wrongAnswers}`, `Rondas perfectas: ${this.save.perfectRounds}`, `Duplicar ganados: ${this.save.duplicateWins}`, `Colección normal: ${this.save.ownedCollectibles.length}/${window.VIVEROBOX_COLLECTIBLES.length}`, `Colección secreta: ${this.save.ownedSecretCollectibles.length}/${window.VIVEROBOX_SECRET_COLLECTIBLES.length}`, `EPIs desbloqueados: ${this.save.ownedEpis.length}/${window.VIVEROBOX_EPIS.length}`]; lines.forEach((l,i)=>this.txt(360,150+i*50,l,27,C.text).setOrigin(0,.5)); this.back();}
 showOptions(){this.state='options'; this.clear(); this.bg(); this.txt(W/2,80,'⚙️ Opciones',44,'#baffcf','center').setOrigin(.5); this.txt(W/2,155,'Nombre del jugador',26,C.text,'center').setOrigin(.5); const inp=document.createElement('input'); inp.className='viverobox-name-input'; inp.value=this.save.playerName; inp.maxLength=18; inp.style.left='calc(50% - 140px)'; inp.style.top='190px'; inp.style.width='280px'; document.body.appendChild(inp); this.btn(W/2,280,220,50,'Guardar nombre',()=>{this.save.playerName=inp.value.trim()||'Gamer'; this.saveNow(); this.showOptions();},{color:0x1f6a3f}); this.btn(W/2,360,260,50,`Sonido: ${this.save.settings.sound?'Sí':'No'}`,()=>{this.save.settings.sound=!this.save.settings.sound; this.saveNow(); this.showOptions();},{color:0x244131}); this.btn(W/2,440,280,50,'Borrar progreso',()=>{localStorage.removeItem(KEY); this.save=getSave(); this.showMenu();},{color:0x503030,stroke:C.red}); this.back();}
 toast(msg){const t=this.txt(W/2,650,msg,24,'#ffdf9e','center').setOrigin(.5); this.tweens.add({targets:t,alpha:0,y:620,duration:1600,onComplete:()=>t.destroy()});}
 particles(x,y,color){for(let i=0;i<28;i++){let p=this.add.circle(x,y,Phaser.Math.Between(3,7),color,.9); this.tweens.add({targets:p,x:x+Phaser.Math.Between(-120,120),y:y+Phaser.Math.Between(-120,80),alpha:0,duration:800,onComplete:()=>p.destroy()});}}
 drawIcon(x,y,it,secret=false,visible=true){if(!visible){this.add.circle(x,y,24,0x27342d,.8); return;} if(secret){this.add.star(x,y,6,12,28,0x6b2ca0).setStrokeStyle(2,0xdcb8ff); return;} const type=it.type||''; if(type==='planta'){this.drawPlant(x,y,.55,it.subtype==='arbol'?'arbol':it.subtype==='arbusto'?'arbusto':'planta');} else if(type==='maquinaria'){this.add.rectangle(x,y+8,58,28,0x46545a).setStrokeStyle(2,0xc9d6d5); this.add.circle(x-20,y+25,8,0x111); this.add.circle(x+20,y+25,8,0x111);} else if(type==='herramienta'){this.add.rectangle(x,y,8,58,0x9b6b3d); this.add.rectangle(x,y-28,44,10,0xb7c0ba);} else if(type==='floristeria'){this.add.circle(x-10,y,14,0xff7aa5); this.add.circle(x+10,y,14,0xffd166); this.add.rectangle(x,y+22,8,35,0x42c77a);} else {this.add.rectangle(x,y,48,38,0x9b6b3d).setStrokeStyle(2,0xffd166);} }
 drawPlant(x,y,scale=1,kind='planta'){this.add.rectangle(x,y+45*scale,14*scale,70*scale,0x7b4b2a); if(kind==='arbol'){this.add.circle(x,y-10*scale,45*scale,0x3fa35b); this.add.circle(x-30*scale,y+5*scale,35*scale,0x2e8547); this.add.circle(x+30*scale,y+5*scale,35*scale,0x4bbf68);} else if(kind==='arbusto'){this.add.circle(x,y+20*scale,38*scale,0x4fbf6f); this.add.circle(x-25*scale,y+28*scale,26*scale,0x3fa35b); this.add.circle(x+25*scale,y+28*scale,26*scale,0x5dd47a);} else {this.add.rectangle(x,y+45*scale,38*scale,18*scale,0x8b5a2b); this.add.ellipse(x,y+18*scale,45*scale,48*scale,0x4fc36a); this.add.circle(x+12*scale,y+2*scale,9*scale,0xff7aa5);} }
 drawAvatar(x,y,s=1){this.add.circle(x,y-95*s,32*s,0xffd6b0); this.add.rectangle(x,y-25*s,70*s,105*s,0x247a4b).setStrokeStyle(2,0xbaffcf); this.add.rectangle(x-45*s,y-10*s,22*s,90*s,0xffd6b0); this.add.rectangle(x+45*s,y-10*s,22*s,90*s,0xffd6b0); this.add.rectangle(x-20*s,y+75*s,24*s,85*s,0x244a35); this.add.rectangle(x+20*s,y+75*s,24*s,85*s,0x244a35); Object.values(this.save.equippedEpis||{}).forEach(id=>{const e=window.VIVEROBOX_EPIS.find(v=>v.id===id); if(!e)return; if(id==='casco')this.add.arc(x,y-125*s,42*s,30*s,Math.PI,0,0xffd166).setStrokeStyle(3,0x8c6d1f); if(id==='gafas')this.add.rectangle(x,y-98*s,55*s,13*s,0x55c7ff,.7).setStrokeStyle(2,0xffffff); if(id==='pantalla')this.add.rectangle(x,y-82*s,66*s,55*s,0xaeefff,.32).setStrokeStyle(2,0xaeefff); if(id==='auditivos'){this.add.circle(x-38*s,y-100*s,12*s,0xffd166);this.add.circle(x+38*s,y-100*s,12*s,0xffd166);} if(id.includes('guantes')){this.add.circle(x-45*s,y+42*s,14*s,0xffd166);this.add.circle(x+45*s,y+42*s,14*s,0xffd166);} if(id==='botas'){this.add.rectangle(x-20*s,y+125*s,35*s,18*s,0x111111);this.add.rectangle(x+20*s,y+125*s,35*s,18*s,0x111111);} if(id==='chaleco')this.add.rectangle(x,y-25*s,80*s,70*s,0xffb000,.35).setStrokeStyle(2,0xfff3a0); if(id==='mascarilla'||id==='respiratoria')this.add.rectangle(x,y-82*s,44*s,18*s,0xffffff,.75); if(id==='pantalon_anticorte')this.add.rectangle(x,y+78*s,70*s,82*s,0x304e9a,.75); });}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#07180f',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[GameScene]});
