/* Jardín de Letras V1 - Phaser 3 */
(function(){
'use strict';
const W=1280,H=720, SAVE_KEY='jardin_de_letras_v1_save';
const COLORS={dark:0x10251b, dark2:0x183826, paper:0xf1e4c8, paper2:0xfff4d8, ink:0x2b2116, green:0x397a48, green2:0x62a05d, gold:0xd6a441, red:0xb74d3f, purple:0x583067, cream:0xf7edcf, blue:0x4d7c91, gray:0x6c6c60};
const ALL_WORDS=(window.WORD_BANK_ORIGINAL||[]).concat(window.WORD_BANK_EXTRA||[]).map(e=>({...e, gridWord:e.answer, playable:e.answer&&e.answer.length>=3&&e.answer.length<=20}));
const WORD_BY_ID=Object.fromEntries(ALL_WORDS.map(e=>[e.id,e]));
const PLAYABLE=ALL_WORDS.filter(e=>e.playable);
const CATEGORIES=[...new Set(ALL_WORDS.map(e=>e.category))].sort((a,b)=>a.localeCompare(b,'es'));
const PROFESSIONAL=['JardinerIA','FloristerIA','Zona Segura','Botánica de Campo','Herbario Ornamental','Almacén del Vivero','Manual de Labores','Clínica Vegetal','Red de Riego','Tierra Viva','Invernadero Vivo','Mesa de Identificación','Paisajismo y Diseño','Mostrador Floral'];
const AULA=['MatematIcAs','CiencIA','EcologIA','QuímIcA','FísIcA','ZoologIA','LibrerIA'];
const SPECIAL=['FantasIA','ZombIA','Criaturas del Jardín','Plantas Imposibles','Herramientas Legendarias','Fenómenos Raros','Enemigos del Códex','Objetos de Aula Gamer','Cocina del Compost','Mercado de Floristería'];
const POWERUPS=[
 {id:'lupa',name:'Lupa de vivero',desc:'Revela una letra extra: las dos primeras letras de una palabra pendiente.',cost:2},
 {id:'regadera',name:'Regadera mental',desc:'Mejora una pista al siguiente nivel.',cost:1},
 {id:'guantes',name:'Guantes de trabajo',desc:'Anula el próximo error.',cost:2},
 {id:'brujula',name:'Brújula de raíces',desc:'Indica la dirección de una palabra pendiente.',cost:3},
 {id:'linterna',name:'Linterna de invernadero',desc:'Ilumina una zona útil del tablero.',cost:3},
 {id:'semilla',name:'Semilla guía',desc:'Marca una letra aleatoria de una palabra pendiente.',cost:2}
];
const RELICS=[
 {id:'libreta',name:'Libreta de campo',desc:'+1 concentración al iniciar expedición.'},
 {id:'botas',name:'Botas firmes',desc:'+1 energía máxima en expedición.'},
 {id:'etiquetadora',name:'Etiquetadora sabia',desc:'La primera palabra muestra subcategoría.'},
 {id:'regadera_antigua',name:'Regadera antigua',desc:'Recupera 1 concentración al completar un nodo.'},
 {id:'hoja_repuesto',name:'Hoja de repuesto',desc:'Una vez, evita perder una expedición.'}
];
function today(){return new Date().toISOString();}
function fmtDate(iso){ if(!iso) return 'No descubierto todavía'; const d=new Date(iso); return d.toLocaleDateString('es-ES'); }
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function pick(arr,n,seed=Math.random()){ const a=[...arr]; for(let i=a.length-1;i>0;i--){const j=Math.floor(((Math.sin(seed*999+i*37)+1)/2)*(i+1)); [a[i],a[j]]=[a[j],a[i]];} return a.slice(0,n); }
function randItem(arr){return arr[Math.floor(Math.random()*arr.length)];}
function initialSave(){ return {version:'1.0', profile:{name:'Jugador/a',createdAt:today()}, codex:{}, items:{}, achievements:{}, stats:{games:0,perfect:0,expeditions:0,boxes:0,missionsDone:0,wordsFound:0}, resources:{seeds:120,dust:0,keys:1,secretKeys:0}, activeGame:null, activeExpedition:null, history:[], settings:{tutorialSeen:false, sound:true}}; }
function loadSave(){ try{ return Object.assign(initialSave(), JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')); }catch(e){ return initialSave(); }}
function saveData(data){ localStorage.setItem(SAVE_KEY, JSON.stringify(data)); }
function textStyle(size=20,color='#2b2116',extra={}){ return {fontFamily:'system-ui, Segoe UI, Arial', fontSize:size+'px', color, ...extra}; }
function masteryName(r){ const c=r?.foundCount||0; if(!r) return 'No descubierta'; if(r.dorada) return 'Dorada'; if(r.experta) return 'Experta'; if(r.dominada) return 'Dominada'; if(c>=3) return 'Reconocida'; return 'Descubierta'; }
function rarityColor(r){ return {Común:COLORS.green2,'Poco común':0x72a7d8,Rara:0x8d66c2,'Épica':0xb15cc8,Legendaria:COLORS.gold,Prohibida:COLORS.purple}[r]||COLORS.green2; }
class JardinScene extends Phaser.Scene{
 constructor(){ super('JardinScene'); this.ui=[]; this.dataSave=loadSave(); this.page=0; this.filter='Todo'; this.tab='Profesional'; }
 preload(){}
 create(){ this.cameras.main.setBackgroundColor(COLORS.dark); this.input.setTopOnly(true); this.showMenu(); }
 persist(){ saveData(this.dataSave); }
 clear(){ this.ui.forEach(o=>{try{o.destroy();}catch(e){}}); this.ui=[]; this.input.off('pointerup'); this.input.off('pointermove'); this.tweens.killAll(); }
 addObj(o){ this.ui.push(o); return o; }
 panel(x,y,w,h,color=COLORS.paper,alpha=1,stroke=COLORS.gold){ const g=this.add.graphics(); g.fillStyle(color,alpha); g.fillRoundedRect(x,y,w,h,18); g.lineStyle(3,stroke,1); g.strokeRoundedRect(x,y,w,h,18); this.addObj(g); return g; }
 label(x,y,txt,size=22,color='#2b2116',align='left',w=0){ const t=this.add.text(x,y,txt,textStyle(size,color,{fontWeight:size>=28?'800':'600',align,wordWrap:{width:w||undefined}})); this.addObj(t); return t; }
 button(x,y,w,h,txt,cb,opts={}){ const g=this.add.graphics(); const base=opts.color||COLORS.green; const over=opts.over||COLORS.green2; g.fillStyle(base,1); g.fillRoundedRect(x,y,w,h,16); g.lineStyle(2,opts.stroke||COLORS.gold,1); g.strokeRoundedRect(x,y,w,h,16); const t=this.add.text(x+w/2,y+h/2,txt,textStyle(opts.size||20,opts.txtColor||'#fff',{fontWeight:'800',align:'center',wordWrap:{width:w-18}})).setOrigin(.5); const zone=this.add.zone(x,y,w,h).setOrigin(0).setInteractive({useHandCursor:true}); zone.on('pointerover',()=>{g.clear(); g.fillStyle(over,1); g.fillRoundedRect(x,y,w,h,16); g.lineStyle(2,opts.stroke||COLORS.gold,1); g.strokeRoundedRect(x,y,w,h,16);});
 zone.on('pointerout',()=>{g.clear(); g.fillStyle(base,1); g.fillRoundedRect(x,y,w,h,16); g.lineStyle(2,opts.stroke||COLORS.gold,1); g.strokeRoundedRect(x,y,w,h,16);});
 zone.on('pointerup',()=>{this.soundBlip(); cb&&cb();}); this.ui.push(g,t,zone); return {g,t,zone}; }
 smallBack(cb){ this.button(24,24,120,44,'← Volver',cb||(()=>this.showMenu()),{color:COLORS.gray,size:18}); }
 decorate(title,subtitle=''){ const bg=this.add.graphics(); bg.fillGradientStyle(0x10251b,0x183826,0x24492f,0x13251b,1); bg.fillRect(0,0,W,H); for(let i=0;i<40;i++){ const x=Math.random()*W,y=Math.random()*H,r=1+Math.random()*3; bg.fillStyle(i%3?0x5a8f4d:0xd2aa56,.18); bg.fillCircle(x,y,r); } this.addObj(bg); this.label(42,36,title,40,'#fff'); if(subtitle) this.label(44,86,subtitle,18,'#f7edcf'); }
 soundBlip(){ if(!this.dataSave.settings.sound) return; try{ const ctx=this.sound.context, osc=ctx.createOscillator(), gain=ctx.createGain(); osc.frequency.value=480; gain.gain.value=.025; osc.connect(gain); gain.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime+.04);}catch(e){} }
 showToast(msg){ const p=this.panel(430,24,420,54,COLORS.dark2,.96,COLORS.gold); const t=this.label(640,51,msg,19,'#fff','center',380).setOrigin(.5); this.time.delayedCall(1800,()=>{p.destroy();t.destroy();}); }
 showMenu(){ this.clear(); this.decorate('Jardín de Letras','Sopas de letras con pistas, Códex, cajas, expediciones y colección.');
  this.panel(50,130,1180,520,COLORS.paper,.96); this.label(86,154,`Hola, ${this.dataSave.profile.name || 'Jugador/a'}`,30,'#2b2116');
  const buttons=[['Jugar misión',()=>this.showContracts()],['Continuar partida',()=>this.resumeGame()],['Expedición',()=>this.showExpedition()],['Códex',()=>this.showCodex()],['Colección',()=>this.showCollection()],['Cajas',()=>this.showBoxes()],['Tienda',()=>this.showShop()],['Mi Jardín',()=>this.showGarden()],['Logros',()=>this.showAchievements()],['Perfil',()=>this.showProfile()],['Tutorial',()=>this.showTutorial()],['Opciones',()=>this.showOptions()]];
  let x=90,y=220; buttons.forEach((b,i)=>{ if(b[0]==='Continuar partida'&&!this.dataSave.activeGame) return; this.button(x,y,245,62,b[0],b[1],{size:20,color:i%2?COLORS.green2:COLORS.green}); x+=285; if(x>950){x=90;y+=84;} });
  this.label(90,595,`Códex: ${Object.keys(this.dataSave.codex).length}/${ALL_WORDS.length} · Semillas: ${this.dataSave.resources.seeds} · Llaves: ${this.dataSave.resources.keys} · Polvo: ${this.dataSave.resources.dust}`,19,'#4b3a20');
 }
 showOptions(){ this.clear(); this.decorate('Opciones','Perfil del jugador, sonido, información del banco y reinicio seguro.'); this.smallBack(); this.panel(90,130,1100,500,COLORS.paper,.96);
  this.label(130,160,'Perfil del jugador',30); this.label(130,210,'Nombre actual:',20); const nameTxt=this.label(300,210,this.dataSave.profile.name||'Jugador/a',22,'#397a48');
  const letters='ABCDEFGHIJKLMNÑOPQRSTUVWXYZÁÉÍÓÚ -'; let temp=this.dataSave.profile.name||'';
  this.button(130,250,270,48,'Cambiar nombre',()=>{ temp=prompt('Nombre del jugador:', temp)||temp; temp=temp.trim().slice(0,22)||'Jugador/a'; this.dataSave.profile.name=temp; this.dataSave.profile.lastUpdatedAt=today(); this.persist(); nameTxt.setText(temp); this.showToast('Nombre guardado'); },{color:COLORS.green});
  this.button(430,250,220,48,this.dataSave.settings.sound?'Sonido: Sí':'Sonido: No',()=>{this.dataSave.settings.sound=!this.dataSave.settings.sound; this.persist(); this.showOptions();},{color:COLORS.blue});
  this.button(130,330,270,48,'Información del banco',()=>this.showDiagnostic(),{color:COLORS.gold,txtColor:'#2b2116'});
  this.button(430,330,270,48,'Borrar partida actual',()=>{ if(confirm('¿Borrar solo la partida actual?')){this.dataSave.activeGame=null;this.persist();this.showToast('Partida actual borrada');}}, {color:COLORS.red});
  this.button(730,330,270,48,'Resetear TODO',()=>{ const code=prompt('Escribe REINICIAR para borrar todo el progreso'); if(code==='REINICIAR'){localStorage.removeItem(SAVE_KEY); this.dataSave=initialSave(); this.persist(); this.showMenu();}}, {color:COLORS.red});
  this.label(130,430,'Consejo',24); this.label(130,468,'El progreso se guarda automáticamente. Cambiar el nombre o el sonido no reinicia la colección.',18,'#4b3a20','left',850);
 }
 showDiagnostic(){ this.clear(); this.decorate('Información del banco','Resumen técnico del banco y del progreso guardado.'); this.smallBack(()=>this.showOptions()); this.panel(100,120,1080,520,COLORS.paper,.96);
  const total=ALL_WORDS.length, playable=PLAYABLE.length, short=ALL_WORDS.filter(e=>e.answer.length<3).length, long=ALL_WORDS.filter(e=>e.answer.length>20).length;
  const cats=CATEGORIES.map(c=>`${c}: ${ALL_WORDS.filter(e=>e.category===c).length} (${PLAYABLE.filter(e=>e.category===c).length} jugables)`).join('\n');
  this.label(140,150,`Total entradas: ${total}\nJugables 3-20 letras: ${playable}\nDescartadas <3: ${short}\nDescartadas >20: ${long}\nObjetos: ${COLLECTION_ITEMS.length}\nLogros: ${ACHIEVEMENTS.length}\nPartida activa: ${this.dataSave.activeGame?'sí':'no'}`,22,'#2b2116');
  this.label(620,150,cats,15,'#2b2116','left',500);
 }
 showTutorial(){ this.clear(); this.decorate('Tutorial','Cinco ideas para jugar.'); this.smallBack(); this.panel(150,130,980,470,COLORS.paper,.96);
  const txt='1. No buscas palabras visibles: resuelves pistas.\n\n2. Arrastra desde la primera letra hasta la última.\n\n3. Cada pista muestra gratis la inicial de la palabra. Las pistas avanzadas y los powerups cuestan Concentración.\n\n4. Cada palabra descubierta entra en tu Códex con fecha de obtención.\n\n5. Puedes guardar y volver al menú sin perder la partida.';
  this.label(210,185,txt,26,'#2b2116','left',860); this.button(500,560,280,54,'Entendido',()=>{this.dataSave.settings.tutorialSeen=true;this.persist();this.showMenu();},{color:COLORS.green}); }
 contractsForTab(){ let cats=this.tab==='Profesional'?PROFESSIONAL:this.tab==='Ciencia/Aula'?AULA:this.tab==='Especiales'?SPECIAL:CATEGORIES; return cats.filter(c=>PLAYABLE.some(e=>e.category===c)); }
 showContracts(){ this.clear(); this.decorate('Contratos','Elige una categoría y acepta una misión con pistas.'); this.smallBack(); ['Profesional','Ciencia/Aula','Especiales','Todo'].forEach((t,i)=>this.button(180+i*230,90,205,42,t,()=>{this.tab=t;this.page=0;this.showContracts();},{color:this.tab===t?COLORS.gold:COLORS.green,txtColor:this.tab===t?'#2b2116':'#fff',size:17}));
  const cats=this.contractsForTab(); const per=6, pages=Math.max(1,Math.ceil(cats.length/per)); this.page=clamp(this.page,0,pages-1); const slice=cats.slice(this.page*per,this.page*per+per);
  slice.forEach((cat,i)=>{ const x=95+(i%3)*390, y=155+Math.floor(i/3)*215; const count=PLAYABLE.filter(e=>e.category===cat).length; this.panel(x,y,340,178,COLORS.paper2,.96,rarityColor(i%3?'Común':'Rara')); this.label(x+20,y+16,cat,22,'#2b2116','left',300); this.label(x+20,y+55,`${count} palabras jugables
Contrato técnico · 7 palabras
Pistas con inicial gratuita
Recompensa: semillas + Códex`,15,'#4b3a20','left',300); this.button(x+72,y+128,195,36,'Aceptar contrato',()=>this.startMission(cat,'mission'),{size:14,color:COLORS.green}); });
  this.pager(500,650,pages,()=>this.showContracts());
 }
 pager(x,y,pages,redraw){ this.button(x-170,y,140,42,'← Anterior',()=>{this.page=clamp(this.page-1,0,pages-1);redraw();},{color:COLORS.gray,size:16}); this.label(x+25,y+10,`Página ${this.page+1} / ${pages}`,18,'#fff'); this.button(x+190,y,140,42,'Siguiente →',()=>{this.page=clamp(this.page+1,0,pages-1);redraw();},{color:COLORS.gray,size:16}); }
 startMission(category,mode='mission',modifier=null){ const pool=PLAYABLE.filter(e=>category==='LoterIA'||category==='Todo'||!category?true:e.category===category); const count=mode==='boss'?10:mode==='expedition'?7+Math.floor(Math.random()*3):7; const words=pick(pool,count,Math.random()).map(e=>({...e, gridWord:e.answer})); let gen; try{ gen=window.generateWordSearch(words,{minPlaced:Math.min(5,count)}); }catch(e){ this.showToast('No se pudo crear la sopa'); return; }
  const active={id:'game_'+Date.now(), mode, category:category||'LoterIA', modifier, board:gen.board, size:gen.size, objectives:gen.objectives.map(o=>({id:o.id, gridWord:o.gridWord, placement:o.placement, found:false, clueLevel:0})), foundPaths:[], energy:mode==='mission'?5:(mode==='boss'?7:8), maxEnergy:mode==='mission'?5:8, concentration:mode==='mission'?7:6, seedsEarned:0, errors:0, usedAdvanced:false, startedAt:today(), powerups:{lupa:1,regadera:1,guantes:1,brujula: mode==='mission'?0:1, linterna:0, semilla:1}, shield:false, selectedObjectiveId:null, finished:false};
  this.dataSave.activeGame=active; this.persist(); this.showGame(); }
 resumeGame(){ if(!this.dataSave.activeGame){this.showToast('No hay partida guardada'); return;} this.showGame(); }
 showGame(){ this.clear(); const g=this.dataSave.activeGame; if(!g){this.showMenu();return;} this.decorate(g.mode==='boss'?'Boss: Diccionario de Raíces':`Contrato: ${g.category}`,`Energía ${g.energy}/${g.maxEnergy} · Concentración ${g.concentration} · Semillas ${g.seedsEarned}`);
  this.button(1030,26,210,44,'Guardar y menú',()=>{this.persist();this.showMenu();},{color:COLORS.gray,size:17}); this.button(880,26,130,44,'Códex',()=>this.showCodex(()=>this.showGame()),{color:COLORS.blue,size:17});
  this.drawBoard(g); this.drawClues(g); this.drawPowerups(g); }
 drawBoard(g){ const maxBoard=560, cell=Math.floor(maxBoard/g.size), ox=52, oy=120; this.boardCells=[]; const boardBg=this.add.graphics(); boardBg.fillStyle(COLORS.paper,.98); boardBg.fillRoundedRect(ox-10,oy-10,cell*g.size+20,cell*g.size+20,18); boardBg.lineStyle(3,COLORS.gold); boardBg.strokeRoundedRect(ox-10,oy-10,cell*g.size+20,cell*g.size+20,18); this.addObj(boardBg);
  const foundSet=new Set(g.foundPaths.flat().map(p=>p.x+','+p.y));
  for(let y=0;y<g.size;y++) for(let x=0;x<g.size;x++){ const rect=this.add.rectangle(ox+x*cell,oy+y*cell,cell-2,cell-2,foundSet.has(x+','+y)?0xb7d99d:0xfff8de).setOrigin(0); rect.setStrokeStyle(1,0xceb36f,.8); const txt=this.add.text(ox+x*cell+cell/2,oy+y*cell+cell/2,g.board[y][x],textStyle(Math.max(15,cell*.48),'#2b2116',{fontWeight:'800'})).setOrigin(.5); const zone=this.add.zone(ox+x*cell,oy+y*cell,cell,cell).setOrigin(0).setInteractive({useHandCursor:true}); zone.cell={x,y}; zone.on('pointerdown',()=>this.startSelect(zone.cell)); zone.on('pointerover',()=>this.moveSelect(zone.cell)); zone.on('pointerup',()=>this.endSelect(zone.cell)); this.ui.push(rect,txt,zone); this.boardCells.push({x,y,rect,txt}); }
 }
 linePath(a,b){ const dx=Math.sign(b.x-a.x), dy=Math.sign(b.y-a.y); if(a.x!==b.x && a.y!==b.y && Math.abs(b.x-a.x)!==Math.abs(b.y-a.y)) return null; const len=Math.max(Math.abs(b.x-a.x),Math.abs(b.y-a.y))+1; const path=[]; for(let i=0;i<len;i++) path.push({x:a.x+dx*i,y:a.y+dy*i}); return path; }
 startSelect(cell){ this.selStart=cell; this.selEnd=cell; this.highlightSelection([cell]); }
 moveSelect(cell){ if(!this.selStart) return; const path=this.linePath(this.selStart,cell); if(path){this.selEnd=cell; this.highlightSelection(path);} }
 endSelect(cell){ if(!this.selStart) return; const g=this.dataSave.activeGame, path=this.linePath(this.selStart,cell); this.selStart=null; this.clearTempHighlights(); if(!path) return; const word=path.map(p=>g.board[p.y][p.x]).join(''); const rev=word.split('').reverse().join(''); const obj=g.objectives.find(o=>!o.found && (o.gridWord===word||o.gridWord===rev)); if(obj){ obj.found=true; obj.foundAt=today(); g.foundPaths.push(obj.placement.path); g.seedsEarned+=10+obj.gridWord.length; this.unlockWord(WORD_BY_ID[obj.id]); this.animateFound(obj.placement.path); this.checkGameEnd(); } else { this.badSelection(word); } this.persist(); this.time.delayedCall(280,()=>this.showGame()); }
 highlightSelection(path){ this.clearTempHighlights(); this.tempHighlights=path.map(p=>{ const c=this.boardCells.find(c=>c.x===p.x&&c.y===p.y); if(c){ c.rect.setFillStyle(0xffdf7a); return c.rect;} return null; }).filter(Boolean); }
 clearTempHighlights(){ if(this.tempHighlights){ const g=this.dataSave.activeGame; const found=new Set((g?.foundPaths||[]).flat().map(p=>p.x+','+p.y)); this.tempHighlights.forEach(r=>{ const c=this.boardCells.find(c=>c.rect===r); if(c) r.setFillStyle(found.has(c.x+','+c.y)?0xb7d99d:0xfff8de);}); } this.tempHighlights=[]; }
 animateFound(path){ path.forEach((p,i)=>{ const c=this.boardCells.find(c=>c.x===p.x&&c.y===p.y); if(c) this.tweens.add({targets:[c.txt],scale:1.45,yoyo:true,duration:130,delay:i*20});}); this.showToast('¡Palabra descubierta!'); }
 badSelection(){ const g=this.dataSave.activeGame; if(g.shield){ g.shield=false; this.showToast('Guantes usados: error anulado'); return;} g.errors++; g.energy--; this.cameras.main.shake(140,.006); if(g.energy<=0){ this.finishGame(false,'Te quedaste sin energía.'); } }
 drawClues(g){ this.panel(665,105,570,395,COLORS.paper,.96); this.label(690,128,'Pistas',28); const pending=g.objectives.filter(o=>!o.found); const shown=g.objectives.slice(0,10); shown.forEach((o,i)=>{ const e=WORD_BY_ID[o.id]; const y=174+i*31; const found=o.found; const initial=o.gridWord?.[0]||'?'; const clue=found?`✅ ${e.display}`:`${i+1}. Inicial ${initial} · ${e.signals[clamp(o.clueLevel,0,3)]}`; const t=this.label(690,y,clue,14,found?'#397a48':'#2b2116','left',500); t.setInteractive({useHandCursor:true}).on('pointerup',()=>{g.selectedObjectiveId=o.id; this.showToast(found?e.display:'Pista seleccionada'); this.persist();}); });
  if(pending.length>10) this.label(690,485,`+${pending.length-10} pistas pendientes`,15,'#4b3a20'); }
 drawPowerups(g){ this.panel(665,520,570,145,COLORS.paper,.96); this.label(690,540,'Powerups consumibles',24); POWERUPS.forEach((p,i)=>{ const x=690+(i%3)*170, y=582+Math.floor(i/3)*42; const qty=g.powerups[p.id]||0; this.button(x,y,156,34,`${p.name.split(' ')[0]} x${qty}`,()=>this.usePowerup(p.id),{size:13,color:qty?COLORS.green:COLORS.gray}); }); }
 usePowerup(id){ const g=this.dataSave.activeGame; if(!g||!(g.powerups[id]>0)){this.showToast('No tienes ese powerup'); return;} const pending=g.objectives.filter(o=>!o.found); if(!pending.length) return; let o=g.selectedObjectiveId?pending.find(x=>x.id===g.selectedObjectiveId):pending[0]; if(!o) o=pending[0]; const e=WORD_BY_ID[o.id]; const cost=(POWERUPS.find(p=>p.id===id)||{}).cost||1; if(g.concentration<cost){this.showToast('Falta concentración'); return;} g.concentration-=cost; g.powerups[id]--;
  if(id==='lupa') this.showToast(`Pista extra: empieza por ${o.gridWord.slice(0, Math.min(2,o.gridWord.length))}`);
  if(id==='regadera'){ o.clueLevel=clamp(o.clueLevel+1,0,3); g.usedAdvanced=true; this.showToast('Pista mejorada'); }
  if(id==='guantes'){ g.shield=true; this.showToast('Próximo error anulado'); }
  if(id==='brujula') this.showToast(`Dirección: ${this.dirName(o.placement.dir)}`);
  if(id==='linterna') this.showToast(`Zona útil cerca de fila ${o.placement.start.y+1}, columna ${o.placement.start.x+1}`);
  if(id==='semilla') { const p=randItem(o.placement.path); this.showToast(`Hay una letra de la palabra en F${p.y+1} C${p.x+1}`); }
  this.persist(); this.showGame(); }
 dirName(d){ if(d.dx===1&&d.dy===0)return 'derecha'; if(d.dx===-1&&d.dy===0)return 'izquierda'; if(d.dx===0&&d.dy===1)return 'abajo'; if(d.dx===0&&d.dy===-1)return 'arriba'; if(d.dx===1&&d.dy===1)return 'diagonal abajo derecha'; if(d.dx===-1&&d.dy===-1)return 'diagonal arriba izquierda'; if(d.dx===1&&d.dy===-1)return 'diagonal arriba derecha'; return 'diagonal abajo izquierda'; }
 checkGameEnd(){ const g=this.dataSave.activeGame; if(g.objectives.every(o=>o.found)){ this.finishGame(true,'Misión completada'); } }
 finishGame(win,msg){ const g=this.dataSave.activeGame; const found=g.objectives.filter(o=>o.found).length; const total=g.objectives.length; let bonus=win?80:Math.floor(g.seedsEarned*.35); if(win&&g.errors===0){bonus+=40; this.dataSave.stats.perfect++;} this.dataSave.resources.seeds += g.seedsEarned + bonus; this.dataSave.stats.games++; if(win&&g.mode==='mission') this.dataSave.stats.missionsDone++; let continueExpedition=false, expeditionFinished=false; if(g.mode==='expedition'){ if(win&&this.dataSave.activeExpedition){ this.dataSave.activeExpedition.node++; this.dataSave.activeExpedition.concentration=Math.min(8,(this.dataSave.activeExpedition.concentration||0)+1); continueExpedition=true; } else { this.dataSave.activeExpedition=null; }} if(g.mode==='boss'){ if(win){ this.dataSave.stats.expeditions++; this.dataSave.resources.secretKeys+=1; expeditionFinished=true; } this.dataSave.activeExpedition=null; } this.dataSave.history.unshift({date:today(),category:g.category,mode:g.mode,found,total,errors:g.errors,seeds:g.seedsEarned+bonus,result:win?'completa':'incompleta'}); this.dataSave.history=this.dataSave.history.slice(0,20); this.updateAchievements(); const summary={win,msg,found,total,errors:g.errors,seeds:g.seedsEarned+bonus,mode:g.mode,continueExpedition,expeditionFinished}; this.dataSave.activeGame=null; this.persist(); this.showReport(summary); }
 showReport(s){ this.clear(); this.decorate('Informe de partida',s.win?'Contrato completado':'Misión incompleta'); this.panel(260,140,760,430,COLORS.paper,.96); const extra=s.expeditionFinished?'\nExpedición completada: +1 llave prohibida.':(s.continueExpedition?'\nLa ruta continúa.':''); this.label(320,190,`${s.msg}\n\nJugador/a: ${this.dataSave.profile.name}\nPalabras: ${s.found}/${s.total}\nErrores: ${s.errors}\nSemillas ganadas: ${s.seeds}\nFecha: ${fmtDate(today())}${extra}`,27,'#2b2116','left',680); this.button(350,480,220,54,'Volver al menú',()=>this.showMenu(),{color:COLORS.green}); if(s.continueExpedition) this.button(610,480,260,54,'Continuar ruta',()=>this.nextExpeditionNode(),{color:COLORS.purple}); else this.button(610,480,260,54,'Nuevo contrato',()=>this.showContracts(),{color:COLORS.gold,txtColor:'#2b2116'}); }
 unlockWord(e,{silent=false}={}){ if(!e) return; const r=this.dataSave.codex[e.id] || {unlocked:true,obtainedAt:today(),foundCount:0,new:true}; r.unlocked=true; if(!r.obtainedAt) r.obtainedAt=today(); r.foundCount=(r.foundCount||0)+1; if(r.foundCount>=3) r.mastery='Reconocida'; if(!this.dataSave.activeGame?.usedAdvanced) r.dominada=true; if(this.dataSave.activeGame?.errors===0) r.dorada=true; this.dataSave.codex[e.id]=r; this.dataSave.stats.wordsFound=Object.keys(this.dataSave.codex).length; if(!silent) this.showToast(`Códex: ${e.display}`); }
 showCodex(backCb){ this.clear(); this.decorate('Códex de Palabras','Colección paginada con fecha de obtención, pistas y maestría.'); this.smallBack(backCb||(()=>this.showMenu())); this.renderGallery('codex', backCb); }
 renderGallery(kind, backCb){ const isCodex=kind==='codex'; const items=isCodex?ALL_WORDS:COLLECTION_ITEMS; const cats=['Todo',...new Set(items.map(i=>i.category))].sort((a,b)=>a==='Todo'?-1:b==='Todo'?1:a.localeCompare(b,'es')); if(!cats.includes(this.filter)) this.filter='Todo'; const filtered=items.filter(it=>this.filter==='Todo'||it.category===this.filter); const per=isCodex?15:16; const pages=Math.max(1,Math.ceil(filtered.length/per)); this.page=clamp(this.page,0,pages-1); this.panel(55,100,1170,550,COLORS.paper,.94); this.button(80,118,130,36,'Todo',()=>{this.filter='Todo';this.page=0; isCodex?this.showCodex(backCb):this.showCollection();},{size:15,color:this.filter==='Todo'?COLORS.gold:COLORS.green,txtColor:this.filter==='Todo'?'#2b2116':'#fff'});
  this.button(225,118,160,36,'Filtro +',()=>{ const idx=cats.indexOf(this.filter); this.filter=cats[(idx+1)%cats.length]; this.page=0; isCodex?this.showCodex(backCb):this.showCollection();},{size:15,color:COLORS.blue}); this.label(410,125,`Filtro: ${this.filter}`,16,'#2b2116');
  filtered.slice(this.page*per,this.page*per+per).forEach((it,i)=>{ const x=90+(i%5)*225, y=175+Math.floor(i/5)*132; const rec=isCodex?this.dataSave.codex[it.id]:this.dataSave.items[it.id]; const unlocked=!!rec; this.panel(x,y,205,105,unlocked?COLORS.paper2:0xc9b990,.98,unlocked?rarityColor(it.rarity):COLORS.gray); const title=unlocked?(isCodex?it.display:it.name):'???'; this.label(x+12,y+12,title,17,unlocked?'#2b2116':'#5f574a','left',180); this.label(x+12,y+40,isCodex?it.category:it.category,13,'#675333','left',180); this.label(x+12,y+62,unlocked?`Obtenido: ${fmtDate(rec.obtainedAt)}\n${isCodex?masteryName(rec):it.rarity}`:'No descubierto todavía',12,'#3d4b2f','left',178); const z=this.add.zone(x,y,205,105).setOrigin(0).setInteractive({useHandCursor:true}); z.on('pointerup',()=>this.tooltip(isCodex?this.wordTooltip(it,rec):this.itemTooltip(it,rec), x+20, y+90)); this.addObj(z); });
  this.pager(510,660,pages,()=>isCodex?this.showCodex(backCb):this.showCollection()); }
 wordTooltip(it,rec){ if(!rec) return 'No descubierto todavía. Encuentra esta palabra en una sopa para revelar su ficha.'; return `${it.display}\nCategoría: ${it.category}\nSubcategoría: ${it.subcategory}\nRareza: ${it.rarity}\nObtenido: ${fmtDate(rec.obtainedAt)}\nEncontrada: ${rec.foundCount||1} veces\nEstado: ${masteryName(rec)}\n\nPista final: ${it.signals?.[3]||''}`; }
 itemTooltip(it,rec){ if(!rec) return 'No descubierto todavía.'; return `${it.name}\nCategoría: ${it.category}\nRareza: ${it.rarity}\nObtenido: ${fmtDate(rec.obtainedAt)}\n\n${it.tooltip}`; }
 tooltip(txt,x,y){ const existing=this.ui.filter(o=>o.name==='tooltip'); existing.forEach(o=>o.destroy()); this.ui=this.ui.filter(o=>o.name!=='tooltip'); const h=170; const px=clamp(x,40,W-430), py=clamp(y,80,H-h-20); const p=this.add.graphics(); p.name='tooltip'; p.fillStyle(COLORS.dark2,.98); p.fillRoundedRect(px,py,390,h,14); p.lineStyle(2,COLORS.gold); p.strokeRoundedRect(px,py,390,h,14); const t=this.add.text(px+18,py+16,txt,textStyle(15,'#fff',{wordWrap:{width:354}})); t.name='tooltip'; this.ui.push(p,t); this.time.delayedCall(4200,()=>{p.destroy();t.destroy();}); }
 showCollection(){ this.clear(); this.decorate('Colección','Objetos, herramientas, plantas, decoración y reliquias.'); this.smallBack(); this.renderGallery('items'); }
 showGarden(){ this.clear(); this.decorate('Mi Jardín','Galería visual básica con tus objetos desbloqueados.'); this.smallBack(); this.panel(70,110,1140,530,COLORS.paper,.94); const owned=COLLECTION_ITEMS.filter(i=>this.dataSave.items[i.id]); this.label(110,140,`Objetos colocados: ${owned.length}/${COLLECTION_ITEMS.length}`,24); const show=owned.slice(0,30); show.forEach((it,i)=>{ const x=120+(i%10)*105,y=205+Math.floor(i/10)*120; const g=this.add.graphics(); g.fillStyle(rarityColor(it.rarity),.9); g.fillCircle(x+35,y+35,30); g.lineStyle(3,COLORS.paper2); g.strokeCircle(x+35,y+35,30); this.addObj(g); this.label(x+35,y+78,it.name.split(' ')[0],12,'#2b2116','center',90).setOrigin(.5,0); }); if(!owned.length) this.label(260,320,'Abre cajas, completa contratos o compra objetos para llenar tu jardín.',26,'#4b3a20','center',760); }
 showBoxes(){ this.clear(); this.decorate('Cajas','Abre cajas: los repetidos se convierten en Polvo de letras.'); this.smallBack(); this.panel(115,140,1050,430,COLORS.paper,.94); const boxes=[['Caja Semillero',80,'normal'],['Caja Herramientas',130,'tool'],['Caja Florista',160,'plant'],['Caja Profesional',220,'relic'],['Caja Prohibida',1,'secret']]; boxes.forEach((b,i)=>{ const x=150+i*205,y=210; this.panel(x,y,170,230,b[2]==='secret'?0x2d1734:COLORS.paper2,.96,b[2]==='secret'?COLORS.purple:COLORS.gold); this.label(x+85,y+35,'📦',44,b[2]==='secret'?'#fff':'#2b2116','center').setOrigin(.5); this.label(x+16,y+92,b[0],18,b[2]==='secret'?'#fff':'#2b2116','center',140); const price=b[2]==='secret'?`${b[1]} llave prohibida`:`${b[1]} semillas`; this.label(x+18,y+143,price,15,b[2]==='secret'?'#f7edcf':'#4b3a20','center',135); this.button(x+25,y+178,120,38,'Abrir',()=>this.openBox(b),{size:15,color:b[2]==='secret'?COLORS.purple:COLORS.green}); }); }
 openBox(b){ const [name,price,type]=b; if(type==='secret'){ if(this.dataSave.resources.secretKeys<price){this.showToast('Falta llave prohibida'); return;} this.dataSave.resources.secretKeys-=price; } else { if(this.dataSave.resources.seeds<price){this.showToast('Faltan semillas'); return;} this.dataSave.resources.seeds-=price; }
  const pool=COLLECTION_ITEMS.filter(i=> type==='secret'?i.secret: type==='plant'?i.category==='Plantas': type==='tool'?i.category==='Herramientas': type==='relic'?i.category==='Reliquias': !i.secret);
  const choices=pick(pool,3,Math.random()); let msg=[]; choices.forEach(it=>{ if(this.dataSave.items[it.id]){this.dataSave.resources.dust+=10; msg.push(`Repetido: ${it.name} (+polvo)`);} else {this.dataSave.items[it.id]={unlocked:true,obtainedAt:today(),new:true}; msg.push(`Nuevo: ${it.name}`);} }); this.dataSave.stats.boxes++; this.updateAchievements(); this.persist(); this.boxReveal(msg); }
 boxReveal(lines){ this.clear(); this.decorate('Caja abierta','Recompensas obtenidas'); this.panel(260,150,760,390,COLORS.paper,.96); lines.forEach((l,i)=>this.label(330,220+i*55,l,25,'#2b2116')); this.button(500,520,280,54,'Seguir abriendo',()=>this.showBoxes(),{color:COLORS.green}); }
 showShop(){ this.clear(); this.decorate('Tienda','Solo aparecen objetos que todavía no tienes.'); this.smallBack(); this.panel(70,110,1140,540,COLORS.paper,.94); const unowned=COLLECTION_ITEMS.filter(i=>!this.dataSave.items[i.id]&&!i.secret); const per=12, pages=Math.max(1,Math.ceil(unowned.length/per)); this.page=clamp(this.page,0,pages-1); unowned.slice(this.page*per,this.page*per+per).forEach((it,i)=>{ const x=105+(i%4)*280,y=155+Math.floor(i/4)*145; this.panel(x,y,250,120,COLORS.paper2,.96,rarityColor(it.rarity)); this.label(x+15,y+14,it.name,18); this.label(x+15,y+44,`${it.category} · ${it.rarity}\n${it.price} semillas`,14,'#4b3a20'); this.button(x+145,y+74,85,34,'Comprar',()=>{ if(this.dataSave.resources.seeds<it.price){this.showToast('Faltan semillas');return;} this.dataSave.resources.seeds-=it.price; this.dataSave.items[it.id]={unlocked:true,obtainedAt:today(),new:true}; this.persist(); this.showShop();},{size:13,color:COLORS.green}); }); this.pager(500,660,pages,()=>this.showShop()); }
 showAchievements(){ this.clear(); this.decorate('Logros','Insignias paginadas con recompensas reclamables.'); this.smallBack(); this.panel(70,110,1140,540,COLORS.paper,.94); const per=12,pages=Math.max(1,Math.ceil(ACHIEVEMENTS.length/per)); this.page=clamp(this.page,0,pages-1); ACHIEVEMENTS.slice(this.page*per,this.page*per+per).forEach((a,i)=>{ const rec=this.dataSave.achievements[a.id]; const x=105+(i%4)*280,y=150+Math.floor(i/4)*150; const done=rec?.done, claimed=rec?.claimed; this.panel(x,y,250,125,done?COLORS.paper2:0xc9b990,.96,done?COLORS.gold:COLORS.gray); this.label(x+15,y+12,done||!a.secret?a.name:'???',18,done?'#2b2116':'#5d5141','left',220); this.label(x+15,y+42,done||!a.secret?a.desc:'Logro secreto',13,'#4b3a20','left',215); this.label(x+15,y+80,done?`Obtenido: ${fmtDate(rec.obtainedAt)}`:'Pendiente',12,'#3d4b2f'); if(done&&!claimed) this.button(x+145,y+82,85,30,'Reclamar',()=>{rec.claimed=true; this.dataSave.resources.seeds+=a.reward; this.persist(); this.showAchievements();},{size:12,color:COLORS.green}); }); this.pager(500,660,pages,()=>this.showAchievements()); }
 updateAchievements(){ const s=this.dataSave.stats, codexCount=Object.keys(this.dataSave.codex).length; ACHIEVEMENTS.forEach(a=>{ if(this.dataSave.achievements[a.id]?.done) return; let done=false; if(a.id.startsWith('words_')) done=codexCount>=parseInt(a.id.split('_')[1]); if(a.id.startsWith('boxes_')) done=s.boxes>=parseInt(a.id.split('_')[1]); if(a.id.startsWith('perfect_')) done=s.perfect>=parseInt(a.id.split('_')[1]); if(a.id.startsWith('exp_')) done=s.expeditions>=parseInt(a.id.split('_')[1]); if(a.id.startsWith('cat_')){ const catName=a.name.replace('Maestría: ',''); done=Object.keys(this.dataSave.codex).filter(id=>WORD_BY_ID[id]?.category===catName).length>=25; } if(done) this.dataSave.achievements[a.id]={done:true,obtainedAt:today(),claimed:false,new:true}; }); }
 showProfile(){ this.clear(); this.decorate('Perfil','Estadísticas, historial y progreso guardado.'); this.smallBack(); this.panel(80,120,520,510,COLORS.paper,.96); this.label(120,155,this.dataSave.profile.name||'Jugador/a',34); const s=this.dataSave.stats; this.label(120,210,`Fecha de inicio: ${fmtDate(this.dataSave.profile.createdAt)}\nPalabras descubiertas: ${Object.keys(this.dataSave.codex).length}\nObjetos conseguidos: ${Object.keys(this.dataSave.items).length}\nLogros desbloqueados: ${Object.values(this.dataSave.achievements).filter(a=>a.done).length}\nSopas jugadas: ${s.games}\nSopas perfectas: ${s.perfect}\nExpediciones completadas: ${s.expeditions}\nSemillas: ${this.dataSave.resources.seeds}`,22,'#2b2116','left',440); this.panel(640,120,560,510,COLORS.paper,.96); this.label(680,155,'Últimas partidas',30); (this.dataSave.history||[]).slice(0,8).forEach((h,i)=>this.label(680,205+i*45,`${fmtDate(h.date)} · ${h.category} · ${h.found}/${h.total} · ${h.result}`,16,'#2b2116','left',500)); }
 showExpedition(){ this.clear(); this.decorate('Expedición','Ruta roguelike con nodos, eventos y boss final sencillo.'); this.smallBack(); this.panel(120,120,1040,500,COLORS.paper,.94); this.label(160,155,'Expedición al Invernadero Oculto',34); this.label(160,205,'Supera nodos de sopa de letras, eventos y una prueba final. Si pierdes energía, termina la run, pero conservas el Códex y los objetos permanentes.',21,'#2b2116','left',920);
  const nodes=['Contrato','Evento','Contrato difícil','Cofre','Nodo secreto','Boss']; nodes.forEach((n,i)=>{ const x=190+i*165,y=360+(i%2)*40; const g=this.add.graphics(); g.fillStyle(i===5?COLORS.purple:COLORS.green,.95); g.fillCircle(x,y,42); g.lineStyle(4,COLORS.gold); g.strokeCircle(x,y,42); this.addObj(g); this.label(x,y-10,i===5?'☠':'✦',28,'#fff','center').setOrigin(.5); this.label(x-65,y+58,n,15,'#2b2116','center',130); if(i<nodes.length-1){ const l=this.add.line(0,0,x+43,y,x+123,360+((i+1)%2)*40,0xd6a441).setOrigin(0); l.setLineWidth(4); this.addObj(l);} });
  this.button(480,565,320,56,'Iniciar expedición',()=>{ this.startExpeditionRun(); },{color:COLORS.purple,size:22}); }
 startExpeditionRun(){ this.dataSave.activeExpedition={node:0,energy:9,maxEnergy:9,concentration:6,relics:pick(RELICS,2).map(r=>r.id),startedAt:today()}; this.persist(); this.nextExpeditionNode(); }
 nextExpeditionNode(){ const ex=this.dataSave.activeExpedition; if(!ex){this.showExpedition(); return;} const cats=['JardinerIA','Zona Segura','Botánica de Campo','Almacén del Vivero','Clínica Vegetal','Red de Riego','Tierra Viva','FloristerIA','FantasIA','ZombIA']; if(ex.node>=5){ this.startMission('LoterIA','boss'); return; } if(ex.node===1||ex.node===3){ this.showEventNode(); return; } this.startMission(randItem(cats),'expedition'); }
 showEventNode(){ this.clear(); this.decorate('Evento de expedición','Elige con cuidado.'); this.panel(230,150,820,420,COLORS.paper,.96); const events=[['Etiqueta mojada','Leerla: +1 concentración','Guardarla: +40 semillas'],['Caja vieja','Abrir: objeto o polvo','Ignorar: +1 energía'],['Niebla verde','Atravesar: +1 llave','Esperar: sin riesgo']]; const ev=randItem(events); this.label(290,210,ev[0],36); this.label(290,265,'Una situación extraña aparece en la ruta del vivero.',22,'#2b2116','left',680); this.button(310,380,270,58,ev[1],()=>{this.eventReward(0);},{color:COLORS.green}); this.button(650,380,270,58,ev[2],()=>{this.eventReward(1);},{color:COLORS.gold,txtColor:'#2b2116'}); }
 eventReward(choice){ const ex=this.dataSave.activeExpedition; if(choice===0){ this.dataSave.resources.keys+=1; this.dataSave.resources.seeds+=25;} else { this.dataSave.resources.seeds+=40; if(ex) ex.energy=Math.min(ex.maxEnergy,ex.energy+1);} if(ex) ex.node++; this.persist(); this.showToast('Evento resuelto'); this.time.delayedCall(350,()=>this.nextExpeditionNode()); }
 showCodexFromGame(){ this.showCodex(()=>this.showGame()); }
}
const config={type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#10251b',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[JardinScene]};
window.addEventListener('load',()=>{ new Phaser.Game(config); });
})();
