import { bg,title,button,panel,small,homeButton,toast } from '../ui/ui.js';
import { AIManager } from '../core/AIManager.js';
import { POWERUPS } from '../data/powerups.js';
import { StorageManager } from '../core/StorageManager.js';
let run=null;
export class CampaignScene extends Phaser.Scene{constructor(){super('Campaign')} init(data){this.resume=data?.resume;this.result=data?.result;} create(){bg(this);homeButton(this);title(this,'CAMPAÑA: CAMINO AL .00',58,48); if(this.resume&&run){this.afterMatch();return;} if(run&&!run.done){this.drawMap();return;} this.drawStart();}
 drawStart(){small(this,640,130,'Roguelike con powerups exclusivos de campaña. Derrotar IA aquí también cuenta para la colección.',22); button(this,410,310,250,74,'Campaña corta\n5 nodos',()=>this.startRun(5)); button(this,640,310,250,74,'Estándar\n8 nodos',()=>this.startRun(8)); button(this,870,310,250,74,'Pesadilla\n10 nodos',()=>this.startRun(10)); this.add.text(640,455,'Powerups permitidos solo aquí: Pulso de Hielo, Segunda Oportunidad, Par Bendito, Cortarrracha y pasivos suaves.',{fontSize:'22px',color:'#dff8ff',align:'center',wordWrap:{width:900}}).setOrigin(.5);}
 startRun(nodes){StorageManager.addStat(this.game.save,'campaignStarts');this.game.persist();run={nodes,total:nodes,index:0,lives:nodes>=10?1:2,coins:0,active:[],passive:[],lastRival:null,done:false}; this.nextNode();}
 afterMatch(){if(!this.result)return this.drawMap(); if(this.result.winner.type==='human'){StorageManager.addStat(this.game.save,'campaignWins');run.coins+=4+this.result.stats.bestStreak;run.index++;run.lastRival=null;this.reward();} else {run.lives--; if(run.lives<=0){this.endRun(false);return;} small(this,640,610,'Perdiste una vida. La campaña sigue, aunque tu ego no.',24);this.time.delayedCall(1200,()=>this.reward(true));}}
 reward(loss=false){this.children.removeAll();bg(this);homeButton(this);title(this,loss?'RECOMPENSA DE RABIA':'RECOMPENSA',70,52); const options=Phaser.Utils.Array.Shuffle([...POWERUPS]).slice(0,3); small(this,640,130,`Vidas: ${run.lives} · Lágrimas del Rival: ${run.coins}`,24); options.forEach((p,i)=>{const x=360+i*280;panel(this,x,330,250,220,.82);this.add.text(x,260,p.icon,{fontSize:'44px'}).setOrigin(.5);this.add.text(x,315,p.name,{fontFamily:'Arial Black',fontSize:'22px',color:'#fff',align:'center',wordWrap:{width:220}}).setOrigin(.5);this.add.text(x,370,p.desc,{fontSize:'18px',color:'#dff8ff',align:'center',wordWrap:{width:210}}).setOrigin(.5);button(this,x,455,170,45,'Elegir',()=>{if(p.type==='active'&&run.active.length<2)run.active.push(p.id); else if(p.type==='passive'&&run.passive.length<3)run.passive.push(p.id); else run.coins+=6; this.drawMap();},0x31ff8a);});}
 nextNode(){this.drawMap();}
 drawMap(){this.children.removeAll();bg(this);homeButton(this);title(this,'MAPA DE CAMPAÑA',55,48); button(this,1045,35,120,42,'Logros',()=>this.scene.start('Achievements',{returnTo:'Campaign'}),0xffd166); button(this,1180,35,145,42,'Colección',()=>this.scene.start('Collection',{returnTo:'Campaign'}),0xffd166); small(this,640,115,`Nodo ${run.index+1}/${run.total} · Vidas ${run.lives} · Powerups: ${run.active.join(', ')||'ninguno'} · Pasivos: ${run.passive.join(', ')||'ninguno'}`,20); if(run.index>=run.total){this.endRun(true);return;} for(let i=0;i<run.total;i++){const x=170+i*(940/(run.total-1));const y=300+Math.sin(i*.9)*70;this.add.circle(x,y,28,i<run.index?0x31ff8a:i===run.index?0xffd166:0x244463).setStrokeStyle(3,0xffffff,.35);this.add.text(x,y,i===run.total-1?'👑':i===run.index?'⚽':'•',{fontSize:'24px'}).setOrigin(.5); if(i>0)this.add.line(0,0,170+(i-1)*(940/(run.total-1)),300+Math.sin((i-1)*.9)*70,x,y,0x26e6ff,.35).setOrigin(0,0);}
 const boss=run.index===run.total-1; const diff=boss?(run.total>=10?'legendary':'hard'):(run.index<2?'easy':run.index<5?'normal':'hard'); const rival=run.lastRival||AIManager.randomRival(diff); run.lastRival=rival; panel(this,640,520,720,110,.75); this.add.text(640,495,`${boss?'JEFE':'RIVAL'}: ${AIManager.fullName(rival)} · ${rival.rarity}`,{fontSize:'25px',color:'#fff'}).setOrigin(.5); this.add.text(640,535,rival.quote,{fontSize:'20px',color:'#ffd166'}).setOrigin(.5); button(this,520,625,250,60,'JUGAR PARTIDO',()=>this.launchMatch(rival),0x31ff8a); button(this,795,625,230,60,'Abandonar run',()=>{run=null;this.drawStart();},0xff4d8d);}
 launchMatch(rival){const camp={passives:run.passive, active:[...run.active], used:[], useEvenPower:false, retryAvailable:false, cutAI:false, iceUntil:0}; this.scene.start('Match',{mode:'campaign',players:[{type:'human',name:'Fran',nick:'Aspirante',score:0},{type:'ai',...rival,score:0}],target:5,returnTo:'Campaign',campaign:camp});}
 endRun(win){this.children.removeAll();bg(this);title(this,win?'CAMPAÑA COMPLETADA':'RUN TERMINADA',80,56); if(win){StorageManager.addStat(this.game.save,'campaignsCompleted');this.game.persist();} this.add.text(640,260,win?'Has sobrevivido al camino. El cronómetro hoy te dejó vivir.':'El camino sigue, tú no.',{fontSize:'28px',color:'#fff',align:'center'}).setOrigin(.5); button(this,640,440,280,62,'Menú principal',()=>this.scene.start('MainMenu')); run=null;}
}
