import { bg,button,panel,homeButton,toast } from '../ui/ui.js';
import { StorageManager } from '../core/StorageManager.js';
import { AIManager } from '../core/AIManager.js';
export class MatchScene extends Phaser.Scene{constructor(){super('Match')} init(cfg){this.cfg=cfg;this.players=cfg.players;this.target=cfg.target||5;this.mode=cfg.mode||'local';this.current=0;this.running=false;this.cent=0;this.turnStreak=0;this.lastRoll='--';this.phase='normal';this.freeHits=[];this.matchStats={direct:0,penalty:0,free:0,miss:0,bestStreak:0};}
 create(){this.game.audio.stopMusic();this.game.audio.startMusic('match');this.game.trash.resetMatch();bg(this);homeButton(this);this.makeHud();this.makeTimer();this.makePanels();this.makePowerups();this.bindControls();this.showMessage(`Turno de ${this.p().name}`,'generic'); if(this.p().type==='ai')this.time.delayedCall(900,()=>this.aiTurn());}
 p(){return this.players[this.current]} rival(){return this.players[1-this.current]}
 makeHud(){panel(this,640,62,850,90,.72);this.scoreText=this.add.text(640,48,'',{fontFamily:'Arial Black',fontSize:'34px',color:'#fff'}).setOrigin(.5);this.turnText=this.add.text(640,90,'',{fontSize:'20px',color:'#bdf7ff'}).setOrigin(.5);this.updateHud(); button(this,1165,36,120,42,'Pausa',()=>this.pauseMenu(),0xff4d8d);}
 makeTimer(){this.timerText=this.add.text(640,270,'0.00',{fontFamily:'Arial Black,Impact',fontSize:'118px',color:'#ffffff',stroke:'#00d8ff',strokeThickness:8}).setOrigin(.5);this.lastText=this.add.text(640,370,'Última tirada: --',{fontSize:'28px',color:'#d8fbff'}).setOrigin(.5);this.stopBtn=button(this,640,535,420,100,'INICIAR',()=>this.primary(),0x31ff8a);}
 makePanels(){this.special=panel(this,640,440,760,90,.65);this.specialText=this.add.text(640,440,'Reglas: .00 GOL · .01-.03 PENALTI · .97-.99 FALTA',{fontSize:'24px',color:'#fff',align:'center'}).setOrigin(.5);this.talk=this.add.text(640,650,'',{fontSize:'23px',color:'#ffd166',align:'center',wordWrap:{width:1100}}).setOrigin(.5);}
 makePowerups(){if(!this.cfg.campaign?.active?.length)return; const labels={ice:'🧊 Pulso',retry:'🔁 Repetir',even:'🟢 Par',cut:'🪓 Cortar'}; this.cfg.campaign.active.forEach((id,i)=>{button(this,930+i*92,535,86,44,labels[id]||id,()=>this.activatePower(id),0xffd166);});}
 activatePower(id){const c=this.cfg.campaign;if(!c||c.used.includes(id))return; c.used.push(id); if(id==='ice')c.iceUntil=performance.now()+2500; if(id==='retry')c.retryAvailable=true; if(id==='even')c.useEvenPower=true; if(id==='cut')c.cutAI=true; StorageManager.addStat(this.game.save,'powerupsUsed'); toast(this,`Powerup activado: ${id}`,'🃏');}
 bindControls(){this.input.keyboard.on('keydown-SPACE',()=>this.primary());this.input.keyboard.on('keydown-ENTER',()=>this.primary());}
 primary(){if(this.p().type==='ai')return; if(!this.running)this.startClock(); else this.stopClock();}
 startClock(){this.phase=this.phase||'normal';this.running=true;this.game.audio.sfx('start');this.stopBtn.setText(this.phase==='normal'?'PARAR':'PARAR TIRADA');this.clockStart=performance.now()+Math.random()*60;}
 update(){if(this.running){let speed=(this.cfg.campaign?.iceUntil||0)>performance.now() ? 45 : 100; this.cent=Math.floor(((performance.now()-this.clockStart)/10)*speed/100)%100;this.timerText.setText('0.'+String(this.cent).padStart(2,'0'));}}
 stopClock(forcedCent=null){this.running=false;this.game.audio.sfx('stop');const c=forcedCent??this.cent;this.lastRoll=c;this.timerText.setText('0.'+String(c).padStart(2,'0'));this.lastText.setText('Última tirada: 0.'+String(c).padStart(2,'0'));this.resolve(c);}
 resolve(c){if(this.phase==='penalty')return this.resolvePenalty(c); if(this.phase==='free')return this.resolveFree(c); if(c===0){this.goal('direct');return;} if(c>=1&&c<=3){this.game.audio.sfx('penalty');this.phase='penalty';this.specialText.setText('🥅 PENALTI: una tirada extra. PAR = GOL · IMPAR = FALLO');this.showMessage(this.game.trash.pick('penaltyStart',{player:this.p().name,rival:this.rival().name}));this.prepareNext();return;} if(c>=97){this.game.audio.sfx('free');this.phase='free';this.freeHits=[];this.specialText.setText('☄️ FALTA: necesitas 3 centésimas PARES seguidas.');this.showMessage(this.game.trash.pick('freeKickStart',{player:this.p().name,rival:this.rival().name}));this.prepareNext();return;} this.miss();}
 resolvePenalty(c){let even=c%2===0; if(this.cfg.campaign?.useEvenPower && !even){even=true; this.cfg.campaign.useEvenPower=false; toast(this,'Par Bendito salvó tu ego','🟢');}
 this.phase='normal'; if(even){this.goal('penalty');this.showMessage(this.game.trash.pick('penaltyGoal',{player:this.p().name,rival:this.rival().name}));} else {this.game.audio.sfx('miss');this.matchStats.miss++;this.showMessage(this.game.trash.pick('penaltyMiss',{player:this.p().name,rival:this.rival().name}));this.changeTurn();}}
 resolveFree(c){let even=c%2===0; if(this.cfg.campaign?.useEvenPower && !even){even=true; this.cfg.campaign.useEvenPower=false; toast(this,'Par Bendito salvó la falta','🟢');}
 this.freeHits.push({c,even}); const marks=this.freeHits.map(x=>x.even?'✅':'❌').join(' ');this.specialText.setText(`☄️ FALTA: ${marks}  (${this.freeHits.length}/3)`); if(!even){this.phase='normal';this.game.audio.sfx('miss');this.matchStats.miss++;this.showMessage(this.game.trash.pick('freeKickMiss',{player:this.p().name,rival:this.rival().name}));this.changeTurn();return;} if(this.freeHits.length>=3){this.phase='normal';this.goal('free');this.showMessage(this.game.trash.pick('freeKickGoal',{player:this.p().name,rival:this.rival().name}));} else this.prepareNext();}
 goal(kind){this.game.audio.sfx('goal');this.p().score++;this.turnStreak++;this.matchStats.bestStreak=Math.max(this.matchStats.bestStreak,this.turnStreak);this.matchStats[kind==='direct'?'direct':kind==='penalty'?'penalty':'free']++;this.updateHud();this.cameras.main.shake(180,.008);this.tweens.add({targets:this.timerText,scale:1.18,duration:120,yoyo:true}); const vars={player:this.p().name,rival:this.rival().name}; if(kind==='direct')this.showMessage(this.game.trash.pick(this.p().type==='ai'?'aiGoal':'playerGoal',vars)); if(this.turnStreak>=2)this.showMessage(this.game.trash.pick('streak',vars)); if(this.target!==999&&this.p().score>=this.target){this.finish();return;} if(this.cfg.campaign?.cutAI && this.p().type==='ai'){this.cfg.campaign.cutAI=false;toast(this,'Cortarrracha usado','🪓');this.changeTurn();return;} this.prepareNext();}
 miss(){this.game.audio.sfx('miss');this.matchStats.miss++;let vars={player:this.p().name,rival:this.rival().name}; if(this.turnStreak>1)this.showMessage(this.game.trash.pick('streakBroken',vars)); else this.showMessage(this.game.trash.pick('miss',vars)); if(this.cfg.campaign?.retryAvailable && this.p().type==='human'){this.cfg.campaign.retryAvailable=false;toast(this,'Segunda Oportunidad: repite la tirada','🔁');this.prepareNext();return;} this.changeTurn();}
 prepareNext(){this.stopBtn.setText(this.p().type==='ai'?'IA pensando...':'INICIAR');this.updateHud(); if(this.p().type==='ai')this.time.delayedCall(850,()=>this.aiTurn());}
 changeTurn(){this.phase='normal';this.freeHits=[];this.turnStreak=0;this.current=1-this.current;this.specialText.setText(`Turno de ${this.p().name}. Si marca, sigue tirando.`);this.updateHud(); if(this.p().type==='ai')this.time.delayedCall(900,()=>this.aiTurn()); else this.stopBtn.setText('INICIAR');}
 aiTurn(){if(this.scene.key!=='Match'||this.p().type!=='ai')return; this.startClock(); const diff=this.p().difficulty||this.cfg.aiDifficulty||'normal'; const human=this.players.find(p=>p.type==='human')||this.players[0]; const ai=this.p(); const forced=AIManager.rollCentisecond(diff,ai.score,human.score,this.turnStreak,this.cfg.campaign?.passives||[]); this.time.delayedCall(600+Math.random()*450,()=>this.stopClock(forced));}
 showMessage(text,cat){this.talk.setText('🎙️ '+text);}
 updateHud(){this.scoreText.setText(`${this.players[0].name} ${this.players[0].score}  -  ${this.players[1].score} ${this.players[1].name}`);this.turnText.setText(`Turno: ${this.p().name} ${this.p().type==='ai'?'🤖':'🧍'} · Racha: ${this.turnStreak}`);}
 pauseMenu(){const c=this.add.container(640,360);const b=this.add.rectangle(0,0,560,330,0x020817,.96).setStrokeStyle(3,0xff4d8d);const tx=this.add.text(0,-105,'PAUSA\n¿Pausa táctica o ataque de pánico?',{fontSize:'28px',color:'#fff',align:'center'}).setOrigin(.5); const a=button(this,640,350,300,54,'Continuar',()=>c.destroy()); const m=button(this,640,425,300,54,'Volver al menú',()=>this.scene.start('MainMenu'),0xff4d8d); c.add([b,tx,a.r,a.t,m.r,m.t]);}
 finish(){this.game.audio.sfx('win'); const winner=this.p(), loser=this.rival(); const s=this.game.save; StorageManager.addStat(s,'goals',this.matchStats.direct+this.matchStats.penalty+this.matchStats.free);StorageManager.addStat(s,'directGoals',this.matchStats.direct);StorageManager.addStat(s,'penaltyGoals',this.matchStats.penalty);StorageManager.addStat(s,'freeKickGoals',this.matchStats.free);StorageManager.setMax(s,'bestStreak',this.matchStats.bestStreak);StorageManager.addStat(s,'wins'); if(this.mode==='local')StorageManager.addStat(s,'localWins'); if(loser.score===0)StorageManager.addStat(s,'shutouts'); if(this.mode==='ai'||this.mode==='campaign'||this.mode==='tournament'){if(winner.type==='human'&&loser.type==='ai'){StorageManager.addStat(s,'aiWins'); const d=loser.difficulty; StorageManager.addStat(s,d==='easy'?'aiEasyWins':d==='normal'?'aiNormalWins':d==='hard'?'aiHardWins':'aiLegendWins'); StorageManager.defeatRival(s,loser.id,this.mode,`${winner.score}-${loser.score}`);} if(winner.type==='ai'){StorageManager.loseToRival(s,winner.id);} }
 StorageManager.recordMatch(s,{winner:winner.name,score:`${this.players[0].score}-${this.players[1].score}`,mode:this.mode}); const newly=this.game.persist(); this.scene.start('Results',{winner,loser,players:this.players,stats:this.matchStats,newly,returnTo:this.cfg.returnTo||'MainMenu',campaign:this.cfg.campaign,tournament:this.cfg.tournament});}
}
