import { bg,title,button,inputBox,homeButton,small } from '../ui/ui.js';
import { AIManager } from '../core/AIManager.js';
export class MatchSetupScene extends Phaser.Scene{constructor(){super('MatchSetup')} init(data){this.mode=data.mode||'local';} create(){bg(this);homeButton(this); title(this,this.mode==='local'?'PARTIDO LOCAL':'VS IA',78,58); this.target=5; this.diff='normal'; this.rivalMode='random'; this.rival=null; this.inputs=[]; if(this.mode==='local'){this.inputs.push(inputBox(this,470,205,290,'Jugador 1','Fran')); this.inputs.push(inputBox(this,810,205,290,'Jugador 2','Rival')); small(this,640,255,'Los dos jugadores comparten dispositivo. Si marcas, sigues tirando.',22);} else {this.inputs.push(inputBox(this,640,190,330,'Tu nombre','Fran')); small(this,640,240,'Humano siempre empieza. Sin powerups. La IA difícil aprieta, pero no hace trampas absurdas.',21); this.addDiffButtons(); this.addRivalButtons(); }
 this.addTargetButtons(); button(this,640,600,340,70,'EMPEZAR PARTIDO',()=>this.startMatch(),0x31ff8a);}
 addTargetButtons(){small(this,640,330,'Objetivo del partido',22); [[5,'5 goles'],[10,'10 goles'],[999,'Infinito']].forEach((v,i)=>button(this,450+i*190,380,160,54,v[1],()=>{this.target=v[0];},0xffd166));}
 addDiffButtons(){small(this,640,315,'Dificultad IA',21); [['easy','Fácil'],['normal','Normal'],['hard','Difícil'],['legendary','Legendario']].forEach((d,i)=>button(this,355+i*185,360,160,48,d[1],()=>{this.diff=d[0];this.rival=null;}));}
 addRivalButtons(){button(this,470,445,250,50,'Rival aleatorio',()=>{this.rivalMode='random';this.rival=null;}); button(this,810,445,250,50,'Revancha IA',()=>{this.rivalMode='known'; const pool=Object.entries(this.game.save.collection).filter(([id,c])=>c.state!=='locked'); if(pool.length){const id=Phaser.Utils.Array.GetRandom(pool)[0]; import('../data/aiRivals.js').then(m=>{this.rival=m.AI_RIVALS.find(r=>r.id===id);});}},0xffd166);}
 startMatch(){this.inputs.forEach(i=>i.el.removeListener?.()); const p1=this.inputs[0].value||'Jugador 1'; let cfg={mode:this.mode,target:this.target,players:[],from:'setup'}; if(this.mode==='local'){cfg.players=[{type:'human',name:p1,nick:'Cazacentésimas',score:0},{type:'human',name:this.inputs[1].value||'Jugador 2',nick:'El Nervios',score:0}];}
 else {let rival=this.rival||AIManager.randomRival(this.diff); cfg.players=[{type:'human',name:p1,nick:'Humano peligroso',score:0},{type:'ai',...rival,score:0}]; cfg.aiDifficulty=rival.difficulty;}
 this.scene.start('Match',cfg);}
 shutdown(){this.inputs?.forEach(i=>i.destroy());}
}
