import { bg,title,button,inputBox,small,homeButton,panel } from '../ui/ui.js';
import { AIManager } from '../core/AIManager.js';
import { TournamentManager } from '../core/TournamentManager.js';
import { StorageManager } from '../core/StorageManager.js';
let tournamentState=null;
export class TournamentScene extends Phaser.Scene{constructor(){super('Tournament')} init(data){this.resume=data?.resume;this.result=data?.result;} create(){bg(this);homeButton(this);title(this,'TORNEO',70,58); if(this.resume&&tournamentState){this.applyResult();this.drawBracket();return;} if(tournamentState&&!tournamentState.champion){this.drawBracket();return;} this.players=[];this.target=5; this.nameInput=inputBox(this,340,165,260,'Nombre humano','Fran'); button(this,610,165,180,50,'+ Humano',()=>{this.players.push({type:'human',name:this.nameInput.value||'Jugador',nick:'Cazacentésimas'});this.redrawList();}); button(this,820,145,180,44,'+ IA fácil',()=>this.addAI('easy'));button(this,820,200,180,44,'+ IA normal',()=>this.addAI('normal'));button(this,1030,145,180,44,'+ IA difícil',()=>this.addAI('hard'));button(this,1030,200,180,44,'Generar 8 IA',()=>{for(let i=0;i<8;i++)this.addAI(['easy','normal','hard'][i%3]);}); small(this,640,260,'Añade humanos e IA. Si no hay potencia de 2, habrá pases automáticos.',21); this.listText=this.add.text(120,305,'',{fontSize:'20px',color:'#fff'}); button(this,440,620,170,52,'A 5 goles',()=>this.target=5); button(this,640,620,170,52,'A 10 goles',()=>this.target=10); button(this,870,620,250,58,'Crear cuadro',()=>this.createTournament(),0x31ff8a); this.redrawList();}
 addAI(diff){const r=AIManager.generateRival(diff);this.players.push({type:'ai',...r});this.redrawList();}
 redrawList(){if(this.listText)this.listText.setText(this.players.map((p,i)=>`${i+1}. ${p.type==='ai'?'🤖':'🧍'} ${AIManager.fullName(p)} ${p.difficulty?'· '+p.difficulty:''}`).join('\n')||'Sin participantes todavía.');}
 createTournament(){if(this.players.length<2)return; tournamentState=TournamentManager.create(this.players);tournamentState.target=this.target;StorageManager.addStat(this.game.save,'tournamentsCreated');this.game.persist();this.drawBracket();}
 applyResult(){const t=tournamentState; const m=t.rounds[t.currentRound].find(x=>!x.done&&((x.a.name===this.result.players[0].name&&x.b.name===this.result.players[1].name)||(x.a.name===this.result.players[1].name&&x.b.name===this.result.players[0].name))); if(m){m.scoreA=this.result.players.find(p=>p.name===m.a.name)?.score??0;m.scoreB=this.result.players.find(p=>p.name===m.b.name)?.score??0;m.winner=this.result.winner;m.done=true; if(this.result.winner.type==='human')StorageManager.addStat(this.game.save,'tournamentMatchesWon'); this.game.persist();} TournamentManager.advance(t);}
 drawBracket(){this.children.removeAll();bg(this);homeButton(this);button(this,1045,35,120,42,'Logros',()=>this.scene.start('Achievements',{returnTo:'Tournament'}),0xffd166);button(this,1180,35,145,42,'Colección',()=>this.scene.start('Collection',{returnTo:'Tournament'}),0xffd166);title(this,'CUADRO DE TORNEO',55,48); const t=tournamentState; if(t.champion){this.add.text(640,260,`🏆 CAMPEÓN: ${AIManager.fullName(t.champion)}`,{fontFamily:'Arial Black',fontSize:'42px',color:'#ffd166',align:'center'}).setOrigin(.5); this.add.text(640,350,this.game.trash.pick('champion',{player:t.champion.name}),{fontSize:'25px',color:'#fff',align:'center',wordWrap:{width:900}}).setOrigin(.5); if(t.champion.type==='human')StorageManager.addStat(this.game.save,'tournamentsWon');this.game.persist(); button(this,640,560,280,60,'Menú principal',()=>this.scene.start('MainMenu')); return;}
 const round=t.rounds[t.currentRound]; this.add.text(640,112,`Ronda ${t.currentRound+1}/${t.rounds.length} · Objetivo: ${t.target} goles`,{fontSize:'24px',color:'#dff8ff'}).setOrigin(.5); round.forEach((m,i)=>{const x=330+(i%2)*620,y=190+Math.floor(i/2)*118; panel(this,x,y,540,88,.75); const label=`${AIManager.fullName(m.a)} ${m.scoreA??''}\nVS\n${AIManager.fullName(m.b)} ${m.scoreB??''}`; this.add.text(x,y,label,{fontSize:'17px',color:m.done?'#9fffc4':'#fff',align:'center'}).setOrigin(.5); if(!m.done&&m.a.type!=='bye'&&m.b.type!=='bye')button(this,x+205,y,95,42,'Jugar',()=>this.playMatch(m),0x31ff8a);}); button(this,510,650,230,52,'Simular IA vs IA',()=>this.simulateAll(),0xffd166); button(this,770,650,230,52,'Abandonar torneo',()=>{tournamentState=null;this.scene.start('Tournament');},0xff4d8d);}
 playMatch(m){if(m.a.type==='ai'&&m.b.type==='ai'){this.simMatch(m);this.drawBracket();return;} const players=[m.a,m.b]; const humanIndex=players.findIndex(p=>p.type==='human'); if(humanIndex===1)players.reverse(); players[0].score=0;players[1].score=0; this.scene.start('Match',{mode:'tournament',players,target:tournamentState.target,returnTo:'Tournament',tournament:true});}
 simMatch(m){const power={easy:1,normal:2,hard:3,legendary:4}; const pa=power[m.a.difficulty]||1,pb=power[m.b.difficulty]||1; const target=tournamentState.target; let a=0,b=0; while(a<target&&b<target){Math.random()<pa/(pa+pb)?a++:b++;} m.scoreA=a;m.scoreB=b;m.winner=a>b?m.a:m.b;m.done=true;}
 simulateAll(){const round=tournamentState.rounds[tournamentState.currentRound];round.forEach(m=>{if(!m.done&&m.a.type==='ai'&&m.b.type==='ai')this.simMatch(m);});TournamentManager.advance(tournamentState);this.drawBracket();}
}
