import { bg,title,button,homeButton,panel,small,toast } from '../ui/ui.js';
import { StorageManager } from '../core/StorageManager.js';
export class TrainingScene extends Phaser.Scene{constructor(){super('Training')} create(){bg(this);homeButton(this);title(this,'ENTRENAMIENTO',70,54); small(this,640,135,'Practica sin presión. Aquí no hay powerups: solo tú y tu dedo llegando tarde.',22); button(this,330,290,260,70,'Práctica libre',()=>this.startMode('free')); button(this,640,290,260,70,'Caza el .00',()=>this.startMode('direct')); button(this,950,290,260,70,'Penaltis',()=>this.startMode('penalty')); button(this,640,410,260,70,'Faltas',()=>this.startMode('freeKick'));}
 startMode(mode){this.children.removeAll();bg(this);homeButton(this);this.mode=mode;this.running=false;this.cent=0;this.tries=0;this.success=0;StorageManager.addStat(this.game.save,'trainingSessions');this.game.persist();title(this,`ENTRENO: ${mode.toUpperCase()}`,50,42);panel(this,640,330,720,300,.72);this.timer=this.add.text(640,260,'0.00',{fontFamily:'Arial Black',fontSize:'100px',color:'#fff',stroke:'#00d8ff',strokeThickness:7}).setOrigin(.5);this.info=this.add.text(640,370,'Pulsa iniciar, para y aprende a sufrir.',{fontSize:'26px',color:'#ffd166',align:'center'}).setOrigin(.5);this.btn=button(this,640,520,330,78,'INICIAR',()=>this.primary(),0x31ff8a);button(this,640,630,230,50,'Salir',()=>this.scene.start('Training'),0xff4d8d);}
 primary(){if(!this.running){this.running=true;this.start=performance.now();this.game.audio.sfx('start');this.btn.setText('PARAR');}else{this.running=false;this.game.audio.sfx('stop');this.tries++;this.resolve(this.cent);this.btn.setText('INICIAR');}}
 update(){if(this.running){this.cent=Math.floor((performance.now()-this.start)/10)%100;this.timer.setText('0.'+String(this.cent).padStart(2,'0'));}}
 resolve(c){let ok=false,msg=''; if(this.mode==='free'){ok=c===0||c<=3||c>=97; msg= ok?'Tirada interesante. No pareces completamente perdido.':'Fallo normal. El cronómetro ni se ha despeinado.';} if(this.mode==='direct'){ok=c===0; msg=ok?'¡.00! Gol directo de entrenamiento.':'No es .00. El ego tendrá que esperar.'; if(ok)StorageManager.addStat(this.game.save,'trainingDirect');}
 if(this.mode==='penalty'){ok=c%2===0; msg=ok?'Par: penalti marcado.':'Impar: penalti al museo del fracaso.';} if(this.mode==='freeKick'){ok=c%2===0; msg=ok?'Par conseguido. En falta necesitarías tres.':'Impar. La barrera sigue riéndose.';} if(ok){this.success++;this.game.audio.sfx('goal');toast(this,msg,'⚽');} else this.game.audio.sfx('miss');this.info.setText(`${msg}\nAciertos: ${this.success}/${this.tries}`);this.game.persist();}
}
